system_ss.add(when: 'CONFIG_AST', if_true: files('ast_pci.c'))
system_ss.add(when: 'CONFIG_DW_SPI_PCI', if_true: files('dw_spi_pci_pci.c'))
system_ss.add(when: 'CONFIG_CI_HDRC_PCI', if_true: files('ci_hdrc_pci_pci.c'))
system_ss.add(when: 'CONFIG_DWC3_PCI', if_true: files('dwc3_pci_pci.c'))
system_ss.add(when: 'CONFIG_I3000_EDAC', if_true: files('i3000_edac_pci.c'))
system_ss.add(when: 'CONFIG_AIC94XX', if_true: files('aic94xx_pci.c'))
system_ss.add(when: 'CONFIG_8250_PERICOM', if_true: files('8250_pericom_pci.c'))
system_ss.add(when: 'CONFIG_CAFE1000_CCIC', if_true: files('cafe1000_ccic_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_SCU', if_true: files('intel_scu_pci.c'))
system_ss.add(when: 'CONFIG_ALIBABA_ENI_VDPA', if_true: files('alibaba_eni_vdpa_pci.c'))
system_ss.add(when: 'CONFIG_I2C_DESIGNWARE_PCI', if_true: files('i2c_designware_pci_pci.c'))
system_ss.add(when: 'CONFIG_I2C_AMD_MP2', if_true: files('i2c_amd_mp2_pci.c'))
system_ss.add(when: 'CONFIG_HME', if_true: files('hme_pci.c'))
system_ss.add(when: 'CONFIG_DWC2_PCI', if_true: files('dwc2_pci_pci.c'))
system_ss.add(when: 'CONFIG_ATP870U', if_true: files('atp870u_pci.c'))
system_ss.add(when: 'CONFIG_EXAR_SERIAL', if_true: files('exar_serial_pci.c'))
system_ss.add(when: 'CONFIG_CX8800', if_true: files('cx8800_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_MID_PWR', if_true: files('intel_mid_pwr_pci.c'))
system_ss.add(when: 'CONFIG_IGBVF', if_true: files('igbvf_pci.c'))
system_ss.add(when: 'CONFIG_CIRRUS_QEMU', if_true: files('cirrus_qemu_pci.c'))
system_ss.add(when: 'CONFIG_HE', if_true: files('he_pci.c'))
system_ss.add(when: 'CONFIG_6XXX', if_true: files('6xxx_pci.c'))
system_ss.add(when: 'CONFIG_AGPGART_INTEL', if_true: files('agpgart_intel_pci.c'))
system_ss.add(when: 'CONFIG_AGPGART_SIS', if_true: files('agpgart_sis_pci.c'))
system_ss.add(when: 'CONFIG_AM53C974', if_true: files('am53c974_pci.c'))
system_ss.add(when: 'CONFIG_ARCMSR', if_true: files('arcmsr_pci.c'))
system_ss.add(when: 'CONFIG_CCP', if_true: files('ccp_pci.c'))
system_ss.add(when: 'CONFIG_I82092AA', if_true: files('i82092aa_pci.c'))
system_ss.add(when: 'CONFIG_INIA100', if_true: files('inia100_pci.c'))
system_ss.add(when: 'CONFIG_ET131X', if_true: files('et131x_pci.c'))
system_ss.add(when: 'CONFIG_3C59X', if_true: files('3c59x_pci.c'))
system_ss.add(when: 'CONFIG_I7CORE_EDAC', if_true: files('i7core_edac_pci.c'))
system_ss.add(when: 'CONFIG_IFCVF', if_true: files('ifcvf_pci.c'))
system_ss.add(when: 'CONFIG_IGB', if_true: files('igb_pci.c'))
system_ss.add(when: 'CONFIG_CASSINI', if_true: files('cassini_pci.c'))
system_ss.add(when: 'CONFIG_HINIC', if_true: files('hinic_pci.c'))
system_ss.add(when: 'CONFIG_420XX', if_true: files('420xx_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_TH_PCI', if_true: files('intel_th_pci_pci.c'))
system_ss.add(when: 'CONFIG_4XXX', if_true: files('4xxx_pci.c'))

system_ss.add(when: 'CONFIG_BNA', if_true: files('bna_pci.c'))
system_ss.add(when: 'CONFIG_ALX', if_true: files('alx_pci.c'))
system_ss.add(when: 'CONFIG_HPWDT', if_true: files('hpwdt_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_1500', if_true: files('addi_apci_1500_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_1516', if_true: files('addi_apci_1516_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI8164', if_true: files('adl_pci8164_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI9111', if_true: files('adl_pci9111_pci.c'))
system_ss.add(when: 'CONFIG_AMPLC_DIO200_PCI', if_true: files('amplc_dio200_pci_pci.c'))
system_ss.add(when: 'CONFIG_AMPLC_PCI236', if_true: files('amplc_pci236_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIMDAS', if_true: files('cb_pcimdas_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIMDDA', if_true: files('cb_pcimdda_pci.c'))
system_ss.add(when: 'CONFIG_CX23885', if_true: files('cx23885_pci.c'))
system_ss.add(when: 'CONFIG_CX88_MPEG_DRIVER_MANAGER', if_true: files('cx88_mpeg_driver_manager_pci.c'))
system_ss.add(when: 'CONFIG_DEFXX', if_true: files('defxx_pci.c'))
system_ss.add(when: 'CONFIG_DWC_XLGMAC', if_true: files('dwc_xlgmac_pci.c'))
system_ss.add(when: 'CONFIG_DWC3_HAPS', if_true: files('dwc3_haps_pci.c'))
system_ss.add(when: 'CONFIG_EPIC100', if_true: files('epic100_pci.c'))
system_ss.add(when: 'CONFIG_F81601', if_true: files('f81601_pci.c'))
system_ss.add(when: 'CONFIG_HAMACHI', if_true: files('hamachi_pci.c'))
system_ss.add(when: 'CONFIG_IA', if_true: files('ia_pci.c'))
system_ss.add(when: 'CONFIG_IBMASM', if_true: files('ibmasm_pci.c'))
system_ss.add(when: 'CONFIG_IGEN6_EDAC', if_true: files('igen6_edac_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_PCH_THERMAL', if_true: files('intel_pch_thermal_pci.c'))
system_ss.add(when: 'CONFIG_K8TEMP', if_true: files('k8temp_pci.c'))
system_ss.add(when: 'CONFIG_LPC_ICH', if_true: files('lpc_ich_pci.c'))
system_ss.add(when: 'CONFIG_MF624', if_true: files('mf624_pci.c'))
system_ss.add(when: 'CONFIG_MOXA', if_true: files('moxa_pci.c'))
system_ss.add(when: 'CONFIG_MTK_T7XX', if_true: files('mtk_t7xx_pci.c'))
system_ss.add(when: 'CONFIG_NI_6527', if_true: files('ni_6527_pci.c'))
system_ss.add(when: 'CONFIG_NI_670X', if_true: files('ni_670x_pci.c'))
system_ss.add(when: 'CONFIG_SATA_MV', if_true: files('sata_mv_pci.c'))
system_ss.add(when: 'CONFIG_TW686X', if_true: files('tw686x_pci.c'))
system_ss.add(when: 'CONFIG_VIA_RHINE', if_true: files('via_rhine_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_1564', if_true: files('addi_apci_1564_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI7250', if_true: files('adl_pci7250_pci.c'))
system_ss.add(when: 'CONFIG_AGILENT_82350B_PCI_DRIVER', if_true: files('agilent_82350b_pci_driver_pci.c'))
system_ss.add(when: 'CONFIG_AGPGART_AMD64', if_true: files('agpgart_amd64_pci.c'))
system_ss.add(when: 'CONFIG_AGPGART_VIA', if_true: files('agpgart_via_pci.c'))
system_ss.add(when: 'CONFIG_AMPLC_PCI263', if_true: files('amplc_pci263_pci.c'))
system_ss.add(when: 'CONFIG_CX25821', if_true: files('cx25821_pci.c'))
system_ss.add(when: 'CONFIG_GSC_HPDI', if_true: files('gsc_hpdi_pci.c'))
system_ss.add(when: 'CONFIG_TW68', if_true: files('tw68_pci.c'))

system_ss.add(when: 'CONFIG_IAVF', if_true: files('iavf_pci.c'))
system_ss.add(when: 'CONFIG_EHCI_PCI', if_true: files('ehci_pci_pci.c'))
system_ss.add(when: 'CONFIG_CP500', if_true: files('cp500_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_1032', if_true: files('addi_apci_1032_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_3XXX', if_true: files('addi_apci_3xxx_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI7X3X', if_true: files('adl_pci7x3x_pci.c'))
system_ss.add(when: 'CONFIG_AMPLC_PCI224', if_true: files('amplc_pci224_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIDAS', if_true: files('cb_pcidas_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI6208', if_true: files('adl_pci6208_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI1710', if_true: files('adv_pci1710_pci.c'))
system_ss.add(when: 'CONFIG_8255_PCI', if_true: files('8255_pci_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI1720', if_true: files('adv_pci1720_pci.c'))
system_ss.add(when: 'CONFIG_CB7210_PCI_DRIVER', if_true: files('cb7210_pci_driver_pci.c'))
system_ss.add(when: 'CONFIG_AMD_SPI_PCI', if_true: files('amd_spi_pci_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI_DIO', if_true: files('adv_pci_dio_pci.c'))
system_ss.add(when: 'CONFIG_INES_GPIB', if_true: files('ines_gpib_pci.c'))
system_ss.add(when: 'CONFIG_DT3000', if_true: files('dt3000_pci.c'))
system_ss.add(when: 'CONFIG_RADEONFB', if_true: files('radeonfb_pci.c'))
system_ss.add(when: 'CONFIG_ATA_GENERIC', if_true: files('ata_generic_pci.c'))
system_ss.add(when: 'CONFIG_ARKFB', if_true: files('arkfb_pci.c'))

system_ss.add(when: 'CONFIG_AMPLC_PCI230', if_true: files('amplc_pci230_pci.c'))
system_ss.add(when: 'CONFIG_ATA_PIIX', if_true: files('ata_piix_pci.c'))
system_ss.add(when: 'CONFIG_B2C2_FLEXCOP_PCI', if_true: files('b2c2_flexcop_pci_pci.c'))
system_ss.add(when: 'CONFIG_DL2K', if_true: files('dl2k_pci.c'))
system_ss.add(when: 'CONFIG_ESAS2R', if_true: files('esas2r_pci.c'))
system_ss.add(when: 'CONFIG_KVASER_PCIEFD', if_true: files('kvaser_pciefd_pci.c'))
system_ss.add(when: 'CONFIG_MWIFIEX_PCIE', if_true: files('mwifiex_pcie_pci.c'))
system_ss.add(when: 'CONFIG_PATA_AMD', if_true: files('pata_amd_pci.c'))
system_ss.add(when: 'CONFIG_PATA_ATIIXP', if_true: files('pata_atiixp_pci.c'))
system_ss.add(when: 'CONFIG_SATA_QSTOR', if_true: files('sata_qstor_pci.c'))
system_ss.add(when: 'CONFIG_SATA_SX4', if_true: files('sata_sx4_pci.c'))

system_ss.add(when: 'CONFIG_ADDI_APCI_2200', if_true: files('addi_apci_2200_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI1723', if_true: files('adv_pci1723_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI1724', if_true: files('adv_pci1724_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI1760', if_true: files('adv_pci1760_pci.c'))
system_ss.add(when: 'CONFIG_ATL2', if_true: files('atl2_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIDAS64', if_true: files('cb_pcidas64_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIDDA', if_true: files('cb_pcidda_pci.c'))
system_ss.add(when: 'CONFIG_CN10K_RNG', if_true: files('cn10k_rng_pci.c'))
system_ss.add(when: 'CONFIG_DMFE', if_true: files('dmfe_pci.c'))
system_ss.add(when: 'CONFIG_HSU_DMA_PCI', if_true: files('hsu_dma_pci_pci.c'))
system_ss.add(when: 'CONFIG_IXGBEVF', if_true: files('ixgbevf_pci.c'))
system_ss.add(when: 'CONFIG_JME', if_true: files('jme_pci.c'))
system_ss.add(when: 'CONFIG_JSM', if_true: files('jsm_pci.c'))
system_ss.add(when: 'CONFIG_K10TEMP', if_true: files('k10temp_pci.c'))
system_ss.add(when: 'CONFIG_KE_COUNTER', if_true: files('ke_counter_pci.c'))
system_ss.add(when: 'CONFIG_KSZ884XP', if_true: files('ksz884xp_pci.c'))
system_ss.add(when: 'CONFIG_MACB_PCI', if_true: files('macb_pci_pci.c'))
system_ss.add(when: 'CONFIG_MDPY_FB', if_true: files('mdpy_fb_pci.c'))
system_ss.add(when: 'CONFIG_NETJET', if_true: files('netjet_pci.c'))
system_ss.add(when: 'CONFIG_NITRO_ENCLAVES', if_true: files('nitro_enclaves_pci.c'))
system_ss.add(when: 'CONFIG_PARPORT_PC', if_true: files('parport_pc_pci.c'))
system_ss.add(when: 'CONFIG_PCI1XXXXGP', if_true: files('PCI1xxxxGP_pci.c'))
system_ss.add(when: 'CONFIG_PCNET32', if_true: files('pcnet32_pci.c'))
system_ss.add(when: 'CONFIG_PD6729', if_true: files('pd6729_pci.c'))
system_ss.add(when: 'CONFIG_PEAK_PCIEFD', if_true: files('peak_pciefd_pci.c'))
system_ss.add(when: 'CONFIG_QAIC', if_true: files('qaic_pci.c'))
system_ss.add(when: 'CONFIG_R592', if_true: files('r592_pci.c'))
system_ss.add(when: 'CONFIG_R6040', if_true: files('r6040_pci.c'))
system_ss.add(when: 'CONFIG_SOLOS', if_true: files('solos_pci.c'))
system_ss.add(when: 'CONFIG_TEHUTI', if_true: files('tehuti_pci.c'))

system_ss.add(when: 'CONFIG_ADL_PCI9118', if_true: files('adl_pci9118_pci.c'))
system_ss.add(when: 'CONFIG_ALCOR_PCI', if_true: files('alcor_pci_pci.c'))
system_ss.add(when: 'CONFIG_BNX2', if_true: files('bnx2_pci.c'))
system_ss.add(when: 'CONFIG_BT8XXGPIO', if_true: files('bt8xxgpio_pci.c'))
system_ss.add(when: 'CONFIG_COM20020', if_true: files('com20020_pci.c'))
system_ss.add(when: 'CONFIG_DW_EDMA_PCIE', if_true: files('dw_edma_pcie_pci.c'))
system_ss.add(when: 'CONFIG_EMU10K1_GAMEPORT', if_true: files('Emu10k1_gameport_pci.c'))
system_ss.add(when: 'CONFIG_FM801_GAMEPORT', if_true: files('FM801_gameport_pci.c'))
system_ss.add(when: 'CONFIG_FST', if_true: files('fst_pci.c'))
system_ss.add(when: 'CONFIG_I3200_EDAC', if_true: files('i3200_edac_pci.c'))
system_ss.add(when: 'CONFIG_I5500_TEMP', if_true: files('i5500_temp_pci.c'))
system_ss.add(when: 'CONFIG_I6300ESB_TIMER', if_true: files('i6300ESB_timer_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_ETH_PCI', if_true: files('intel_eth_pci_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_IPU7', if_true: files('intel_ipu7_pci.c'))
system_ss.add(when: 'CONFIG_IPMI_SI', if_true: files('ipmi_si_pci.c'))
system_ss.add(when: 'CONFIG_IPU3_CIO2', if_true: files('ipu3_cio2_pci.c'))
system_ss.add(when: 'CONFIG_ISDN_INFINEON_PCI', if_true: files('ISDN_Infineon_pci_pci.c'))
system_ss.add(when: 'CONFIG_ISMT_SMBUS', if_true: files('ismt_smbus_pci.c'))

system_ss.add(when: 'CONFIG_KVASER_PCI', if_true: files('kvaser_pci_pci.c'))
system_ss.add(when: 'CONFIG_LABPC_PCI', if_true: files('labpc_pci_pci.c'))
system_ss.add(when: 'CONFIG_LOONGSON', if_true: files('loongson_pci.c'))
system_ss.add(when: 'CONFIG_LOONGSON_SPI_PCI', if_true: files('loongson_spi_pci_pci.c'))
system_ss.add(when: 'CONFIG_MATROX_W1', if_true: files('matrox_w1_pci.c'))
system_ss.add(when: 'CONFIG_MIPI_I3C_HCI_PCI', if_true: files('mipi_i3c_hci_pci_pci.c'))
system_ss.add(when: 'CONFIG_MPI3MR', if_true: files('mpi3mr_pci.c'))
system_ss.add(when: 'CONFIG_NATSEMI', if_true: files('natsemi_pci.c'))
system_ss.add(when: 'CONFIG_NETX', if_true: files('netx_pci.c'))
system_ss.add(when: 'CONFIG_NFORCE2_SMBUS', if_true: files('nForce2_smbus_pci.c'))
system_ss.add(when: 'CONFIG_NI_65XX', if_true: files('ni_65xx_pci.c'))
system_ss.add(when: 'CONFIG_NOZOMI', if_true: files('nozomi_pci.c'))

system_ss.add(when: 'CONFIG_PCH_PHUB', if_true: files('pch_phub_pci.c'))
system_ss.add(when: 'CONFIG_PCH_SPI', if_true: files('pch_spi_pci.c'))
system_ss.add(when: 'CONFIG_PCH_UART', if_true: files('pch_uart_pci.c'))
system_ss.add(when: 'CONFIG_PCI1XXXX_SERIAL', if_true: files('pci1xxxx_serial_pci.c'))
system_ss.add(when: 'CONFIG_PCIE_MP2_AMD', if_true: files('pcie_mp2_amd_pci.c'))
system_ss.add(when: 'CONFIG_PCIPS2', if_true: files('pcips2_pci.c'))
system_ss.add(when: 'CONFIG_PCI_DAS08', if_true: files('pci_das08_pci.c'))
system_ss.add(when: 'CONFIG_PCI_IDIO_16', if_true: files('pci_idio_16_pci.c'))
system_ss.add(when: 'CONFIG_PCI_PF_STUB', if_true: files('pci_pf_stub_pci.c'))
system_ss.add(when: 'CONFIG_PIIX4_SMBUS', if_true: files('piix4_smbus_pci.c'))
system_ss.add(when: 'CONFIG_PRESTERA_DX', if_true: files('Prestera_DX_pci.c'))
system_ss.add(when: 'CONFIG_PVPANIC_PCI', if_true: files('pvpanic_pci_pci.c'))
system_ss.add(when: 'CONFIG_PWM_DWC', if_true: files('pwm_dwc_pci.c'))
system_ss.add(when: 'CONFIG_PWM_LPSS', if_true: files('pwm_lpss_pci.c'))
system_ss.add(when: 'CONFIG_QLA3XXX', if_true: files('qla3xxx_pci.c'))
system_ss.add(when: 'CONFIG_SAA7134', if_true: files('saa7134_pci.c'))
system_ss.add(when: 'CONFIG_SAA7164', if_true: files('saa7164_pci.c'))
system_ss.add(when: 'CONFIG_SATA_SVW', if_true: files('sata_svw_pci.c'))
system_ss.add(when: 'CONFIG_SATA_VIA', if_true: files('sata_via_pci.c'))
system_ss.add(when: 'CONFIG_SC92031', if_true: files('sc92031_pci.c'))
system_ss.add(when: 'CONFIG_SERIAL', if_true: files('serial_pci.c'))
system_ss.add(when: 'CONFIG_SJA1000_PLX_PCI', if_true: files('sja1000_plx_pci_pci.c'))
system_ss.add(when: 'CONFIG_SKFDDI', if_true: files('skfddi_pci.c'))
system_ss.add(when: 'CONFIG_SMSC9420', if_true: files('smsc9420_pci.c'))
system_ss.add(when: 'CONFIG_SNR_UNCORE', if_true: files('snr_uncore_pci.c'))

system_ss.add(when: 'CONFIG_ATH9K_PCI_OWL_LOADER', if_true: files('ath9k_pci_owl_loader_pci.c'))
system_ss.add(when: 'CONFIG_CB710', if_true: files('cb710_pci.c'))
system_ss.add(when: 'CONFIG_CSIOSTOR', if_true: files('csiostor_pci.c'))
system_ss.add(when: 'CONFIG_C_CAN_PCI', if_true: files('c_can_pci_pci.c'))
system_ss.add(when: 'CONFIG_FSL_ENETC_VF', if_true: files('fsl_enetc_vf_pci.c'))
system_ss.add(when: 'CONFIG_IDPF', if_true: files('idpf_pci.c'))
system_ss.add(when: 'CONFIG_STARFIRE', if_true: files('starfire_pci.c'))
system_ss.add(when: 'CONFIG_STMMACETH', if_true: files('stmmaceth_pci.c'))
system_ss.add(when: 'CONFIG_TG3', if_true: files('tg3_pci.c'))
system_ss.add(when: 'CONFIG_THUNDER_BGX', if_true: files('thunder_bgx_pci.c'))
system_ss.add(when: 'CONFIG_THUNDER_XCV', if_true: files('thunder_xcv_pci.c'))
system_ss.add(when: 'CONFIG_TIFM_7XX1', if_true: files('tifm_7xx1_pci.c'))
system_ss.add(when: 'CONFIG_TLAN', if_true: files('tlan_pci.c'))
system_ss.add(when: 'CONFIG_TOSHSD', if_true: files('toshsd_pci.c'))
system_ss.add(when: 'CONFIG_VIA_SDMMC', if_true: files('via_sdmmc_pci.c'))
system_ss.add(when: 'CONFIG_VIA_VELOCITY', if_true: files('via_velocity_pci.c'))
system_ss.add(when: 'CONFIG_VT8231', if_true: files('vt8231_pci.c'))
system_ss.add(when: 'CONFIG_WANXL', if_true: files('wanXL_pci.c'))
system_ss.add(when: 'CONFIG_X38_EDAC', if_true: files('x38_edac_pci.c'))
system_ss.add(when: 'CONFIG_XIRCOM_CB', if_true: files('xircom_cb_pci.c'))

system_ss.add(when: 'CONFIG_INTEL_VPU', if_true: files('intel_vpu_pci.c'))
system_ss.add(when: 'CONFIG_LEDS_SS4200', if_true: files('leds_ss4200_pci.c'))
system_ss.add(when: 'CONFIG_MDIO_THUNDER', if_true: files('mdio_thunder_pci.c'))
system_ss.add(when: 'CONFIG_MEI_TXE', if_true: files('mei_txe_pci.c'))
system_ss.add(when: 'CONFIG_MT7615E', if_true: files('mt7615e_pci.c'))
system_ss.add(when: 'CONFIG_MT76X0E', if_true: files('mt76x0e_pci.c'))
system_ss.add(when: 'CONFIG_MT76X2E', if_true: files('mt76x2e_pci.c'))
system_ss.add(when: 'CONFIG_NTB_HW_AMD', if_true: files('ntb_hw_amd_pci.c'))
system_ss.add(when: 'CONFIG_PLX_DMA', if_true: files('plx_dma_pci.c'))
system_ss.add(when: 'CONFIG_R8169', if_true: files('r8169_pci.c'))
system_ss.add(when: 'CONFIG_RT2400PCI', if_true: files('rt2400pci_pci.c'))
system_ss.add(when: 'CONFIG_RTL8188EE', if_true: files('rtl8188ee_pci.c'))
system_ss.add(when: 'CONFIG_RTL8192CE', if_true: files('rtl8192ce_pci.c'))
system_ss.add(when: 'CONFIG_RTL8192DE', if_true: files('rtl8192de_pci.c'))
system_ss.add(when: 'CONFIG_RTL8192EE', if_true: files('rtl8192ee_pci.c'))
system_ss.add(when: 'CONFIG_RTL8723AE', if_true: files('rtl8723ae_pci.c'))
system_ss.add(when: 'CONFIG_RTL8723BE', if_true: files('rtl8723be_pci.c'))
system_ss.add(when: 'CONFIG_RTL8821AE', if_true: files('rtl8821ae_pci.c'))
system_ss.add(when: 'CONFIG_SND_AZT3328', if_true: files('snd_azt3328_pci.c'))
system_ss.add(when: 'CONFIG_SND_CA0106', if_true: files('snd_ca0106_pci.c'))
system_ss.add(when: 'CONFIG_SND_CMIPCI', if_true: files('snd_cmipci_pci.c'))
system_ss.add(when: 'CONFIG_SND_FM801', if_true: files('snd_fm801_pci.c'))
system_ss.add(when: 'CONFIG_SND_HDA_INTEL', if_true: files('snd_hda_intel_pci.c'))
system_ss.add(when: 'CONFIG_SND_INTEL8X0M', if_true: files('snd_intel8x0m_pci.c'))
system_ss.add(when: 'CONFIG_SND_KORG1212', if_true: files('snd_korg1212_pci.c'))
system_ss.add(when: 'CONFIG_SND_MAESTRO3', if_true: files('snd_maestro3_pci.c'))
system_ss.add(when: 'CONFIG_SND_PCI_ACP6X', if_true: files('snd_pci_acp6x_pci.c'))
system_ss.add(when: 'CONFIG_SND_RME9652', if_true: files('snd_rme9652_pci.c'))
system_ss.add(when: 'CONFIG_SND_RME96', if_true: files('snd_rme96_pci.c'))
system_ss.add(when: 'CONFIG_SND_RPL_PCI_ACP6X', if_true: files('snd_rpl_pci_acp6x_pci.c'))
system_ss.add(when: 'CONFIG_SND_SOC_AVS', if_true: files('snd_soc_avs_pci.c'))
system_ss.add(when: 'CONFIG_SND_SOF_AMD_ACP70', if_true: files('snd_sof_amd_acp70_pci.c'))
system_ss.add(when: 'CONFIG_SND_SONICVIBES', if_true: files('snd_sonicvibes_pci.c'))
system_ss.add(when: 'CONFIG_SND_VIA82XX_MODEM', if_true: files('snd_via82xx_modem_pci.c'))

system_ss.add(when: 'CONFIG_8139CP', if_true: files('8139cp_pci.c'))
system_ss.add(when: 'CONFIG_8139TOO', if_true: files('8139too_pci.c'))
system_ss.add(when: 'CONFIG_8250_LPSS', if_true: files('8250_lpss_pci.c'))
system_ss.add(when: 'CONFIG_8250_MID', if_true: files('8250_mid_pci.c'))
system_ss.add(when: 'CONFIG_AECTC', if_true: files('aectc_pci.c'))
system_ss.add(when: 'CONFIG_AHCI', if_true: files('ahci_pci.c'))
system_ss.add(when: 'CONFIG_BOCHS_DRM', if_true: files('bochs_drm_pci.c'))
system_ss.add(when: 'CONFIG_BT878', if_true: files('bt878_pci.c'))
system_ss.add(when: 'CONFIG_BTTV', if_true: files('bttv_pci.c'))
system_ss.add(when: 'CONFIG_C6XXVF', if_true: files('c6xxvf_pci.c'))
system_ss.add(when: 'CONFIG_CARMINEFB', if_true: files('carminefb_pci.c'))
system_ss.add(when: 'CONFIG_CX18', if_true: files('cx18_pci.c'))
system_ss.add(when: 'CONFIG_CX88_AUDIO', if_true: files('cx88_audio_pci.c'))
system_ss.add(when: 'CONFIG_DE2104X', if_true: files('de2104x_pci.c'))
system_ss.add(when: 'CONFIG_EC_BHF', if_true: files('ec_bhf_pci.c'))
system_ss.add(when: 'CONFIG_EFA', if_true: files('efa_pci.c'))
system_ss.add(when: 'CONFIG_FEALNX', if_true: files('fealnx_pci.c'))
system_ss.add(when: 'CONFIG_GXT4500', if_true: files('gxt4500_pci.c'))
system_ss.add(when: 'CONFIG_HPILO', if_true: files('hpilo_pci.c'))
system_ss.add(when: 'CONFIG_I740FB', if_true: files('i740fb_pci.c'))
system_ss.add(when: 'CONFIG_IE31200_EDAC', if_true: files('ie31200_edac_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_LPSS', if_true: files('intel_lpss_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_QEP', if_true: files('intel_qep_pci.c'))
system_ss.add(when: 'CONFIG_IOSF_MBI_PCI', if_true: files('iosf_mbi_pci_pci.c'))
system_ss.add(when: 'CONFIG_ML_IOH_GPIO', if_true: files('ml_ioh_gpio_pci.c'))
system_ss.add(when: 'CONFIG_MXSER', if_true: files('mxser_pci.c'))
system_ss.add(when: 'CONFIG_NS83820', if_true: files('ns83820_pci.c'))
system_ss.add(when: 'CONFIG_PCWD_PCI', if_true: files('pcwd_pci_pci.c'))
system_ss.add(when: 'CONFIG_PDC_ADMA', if_true: files('pdc_adma_pci.c'))
system_ss.add(when: 'CONFIG_PHANTOM', if_true: files('phantom_pci.c'))
system_ss.add(when: 'CONFIG_R852', if_true: files('r852_pci.c'))
system_ss.add(when: 'CONFIG_SATA_SIL24', if_true: files('sata_sil24_pci.c'))
system_ss.add(when: 'CONFIG_SM501', if_true: files('sm501_pci.c'))
system_ss.add(when: 'CONFIG_SMTCFB', if_true: files('smtcfb_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_MTL', if_true: files('sof_audio_pci_intel_mtl_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_SKL', if_true: files('sof_audio_pci_intel_skl_pci.c'))
system_ss.add(when: 'CONFIG_DDBRIDGE', if_true: files('Southbridge_pci.c'))
system_ss.add(when: 'CONFIG_ULI526X', if_true: files('uli526x_pci.c'))
system_ss.add(when: 'CONFIG_WDT_PCI', if_true: files('wdt_pci_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_CNL', if_true: files('sof_audio_pci_intel_cnl_pci.c'))
