/*
 * QEMU PCI device model for Qualcomm QAIC accelerators - Behavioral Phase
 * Autogenerated model based strictly on linux/drivers/accel/qaic/qaic_drv.c
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "qemu/module.h"
#include "qemu/timer.h"
#include "qemu/log.h"
#include "qemu/host-utils.h"
#include "qapi/error.h"
#include "exec/memory.h"
#include "sysemu/dma.h"
#include "hw/pci/pci.h"
#include "hw/pci/msi.h"
#include "hw/pci/msix.h"
#include "hw/pci/pcie.h"
#include "hw/qdev-properties.h"
#include "hw/qdev-core.h"
#include "migration/vmstate.h"

/* Additional include files retrieved from driver context */
#include "hw/pci/pci_ids.h"

#define TYPE_PCIBASE_DEVICE "qaic_pci"
typedef struct PCIBaseState PCIBaseState;
OBJECT_DECLARE_SIMPLE_TYPE(PCIBaseState, PCIBASE_DEVICE)

/* Register Layout and Hardware Identifiers extracted from driver source */
#define QAIC_PCI_VENDOR_ID            0x17cb
#define QAIC_PCI_DEVICE_ID_AIC080     0xa080

#define QAIC_PCI_CLASS_ACCEL          PCI_CLASS_OTHERS

#define QAIC_DBC_SIZE                 (4 * KiB)
#define QAIC_DBC_BASE                 (128 * KiB)

/* BAR usage derived from qaic_device_config in driver:
 * - For the AIC080-like config we model: bar_mask = BIT(0) | BIT(2) | BIT(4)
 *   mhi_bar_idx = 0, dbc_bar_idx = 2
 * The driver only ioremaps BARs; it does not touch any specific registers in
 * this file, so we only need MMIO regions that exist and are accessible.
 */

typedef enum {
    BAR_TYPE_NONE = 0,
    BAR_TYPE_MMIO,
    BAR_TYPE_PIO,
    BAR_TYPE_RAM 
} BARType;

typedef struct {
    int     index;    /* BAR index 0-5 */
    BARType type;
    hwaddr  size;
    const char *name;
} BARInfo;

struct PCIBaseState {
    PCIDevice parent_obj;

    /* Resource Management */
    MemoryRegion bar_regions[6];
    BARInfo bar_info[6];
    int num_bars;

    /* Capability and Interrupt State */
    bool has_msi;
    bool has_msix;

    /* Hardware Register Shadows (The 'Identity' of the device) */
    /* The qaic_drv.c file provided does not access any explicit device
     * registers; it only ioremaps BARs and hands them to the MHI core or
     * derives per-channel DBC bases as:
     *   qdev->dbc[i].dbc_base = qdev->bar_dbc + QAIC_DBC_OFF(i);
     * Since QAIC_DBC_OFF() is not defined in this file and no MMIO reads or
     * writes are shown, we do not model any specific register set here.
     */

    /* DMA Context */
    /* The driver file provided does not show any direct pci_dma_read or
     * pci_dma_write style hardware-initiated DMA descriptors; higher level
     * MHI and datapath logic is in other source files. Therefore, we do not
     * model any DMA engines here.
     */
};


/* Internal helper for status-triggered signaling. G_GNUC_UNUSED prevents compiler warnings if unused. */
G_GNUC_UNUSED static void pcibase_update_irq(PCIBaseState *s)
{
    /*
     * The qaic_drv.c file does not implement any MMIO interrupt status
     * registers or W1C logic. Interrupts for the QAIC device are entirely
     * managed in the host side by pci_alloc_irq_vectors() and
     * devm_request_threaded_irq(), which are CPU-visible only and do not
     * require device-side MMIO manipulation in this file.
     *
     * As such, there is no device-side interrupt status to track or to
     * signal based on MMIO. We leave this helper empty.
     */
    (void)s;
}

/* Device-initiated DMA logic based on driver access patterns */
G_GNUC_UNUSED static void pcibase_do_dma(PCIBaseState *s, bool is_write)
{
    /*
     * No explicit hardware DMA descriptors or data-path MMIO programming
     * are visible in qaic_drv.c. DMA and data movement appear to be handled
     * by higher-level subsystems (MHI framework, DRM, etc.), none of which
     * program this device via MMIO in the provided source.
     *
     * Consequently, there is no device-initiated DMA to emulate here.
     */
    (void)s;
    (void)is_write;
}

/* MMIO/PIO Handlers generated during Behavioral Modeling */
static uint64_t pcibase_mmio_read(void *opaque, hwaddr addr, unsigned size)
{
    PCIBaseState *s = opaque;
    uint64_t val = 0;

    /*
     * The driver fragment provided never performs readl/ ioreadX() on any
     * specific offsets. BARs are ioremapped and passed into the MHI
     * framework and other subsystems. Without additional driver code that
     * touches explicit register addresses, we must keep MMIO behavior
     * minimal: return zero for all locations.
     *
     * This is sufficient to let the driver ioremap the BARs and to avoid
     * faults on speculative or diagnostic reads.
     */

    (void)s;
    (void)addr;
    (void)size;

    return val;
}

static void pcibase_mmio_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
    PCIBaseState *s = opaque;

    /*
     * As with reads, qaic_drv.c does not show any writes to device-specific
     * registers. The BARs are simply mapped and their addresses are used as
     * opaque pointers by other frameworks.
     *
     * Therefore, we accept writes but ignore them. This avoids triggering
     * errors on harmless probing writes.
     */

    (void)s;
    (void)addr;
    (void)val;
    (void)size;
}

static uint64_t pcibase_pio_read(void *opaque, hwaddr addr, unsigned size)
{
    PCIBaseState *s = opaque;
    uint64_t val = 0;

    /*
     * The QAIC driver only uses memory BARs (IORESOURCE_MEM) and does not
     * perform any port I/O accesses. This handler should never be called,
     * but we provide a benign implementation that returns zero.
     */

    (void)s;
    (void)addr;
    (void)size;

    return val;
}

static void pcibase_pio_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
    PCIBaseState *s = opaque;
    (void)s;
    (void)addr;
    (void)val;
    (void)size;
    /* No PIO is expected or modeled. */
}

static const MemoryRegionOps pcibase_mmio_ops = {
    .read = pcibase_mmio_read,
    .write = pcibase_mmio_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = { .min_access_size = 1, .max_access_size = 8 },
    .impl  = { .min_access_size = 1, .max_access_size = 8 },
};

static const MemoryRegionOps pcibase_pio_ops = {
    .read = pcibase_pio_read,
    .write = pcibase_pio_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = { .min_access_size = 1, .max_access_size = 4 },
    .impl  = { .min_access_size = 1, .max_access_size = 4 },
};

static void pcibase_reset(DeviceState *dev)
{
    PCIBaseState *s = PCIBASE_DEVICE(dev);
    pci_device_reset(PCI_DEVICE(dev));

    /* No additional device state to reset because no registers are modeled
     * from the provided source. If additional sources later show explicit
     * register usage, corresponding reset logic can be added here.
     */

    (void)s;
}

static void pcibase_register_bar(PCIDevice *pdev, PCIBaseState *s, BARInfo *bi, Error **errp)
{
    if (!bi || bi->type == BAR_TYPE_NONE) {
        return;
    }
    
    /* CRITICAL: PCI requires BAR sizes to be a power of 2. Prevent QEMU assert crash. */
    hwaddr aligned_size = pow2ceil(bi->size);
    MemoryRegion *mr = &s->bar_regions[bi->index];

    if (bi->type == BAR_TYPE_MMIO) {
        memory_region_init_io(mr, OBJECT(s), &pcibase_mmio_ops, s, bi->name, aligned_size);
        pci_register_bar(pdev, bi->index, PCI_BASE_ADDRESS_SPACE_MEMORY, mr);
    } else if (bi->type == BAR_TYPE_PIO) {
        memory_region_init_io(mr, OBJECT(s), &pcibase_pio_ops, s, bi->name, aligned_size);
        pci_register_bar(pdev, bi->index, PCI_BASE_ADDRESS_SPACE_IO, mr);
    } else if (bi->type == BAR_TYPE_RAM) {
        memory_region_init_ram(mr, OBJECT(s), bi->name, aligned_size, errp);
        pci_register_bar(pdev, bi->index, PCI_BASE_ADDRESS_SPACE_MEMORY, mr);
    }
}

static void pcibase_realize(PCIDevice *pdev, Error **errp)
{
    PCIBaseState *s = PCIBASE_DEVICE(pdev);
    uint8_t *pci_conf = pdev->config;

    /* Static PCI configuration */
    pci_set_word(pci_conf + PCI_VENDOR_ID,  QAIC_PCI_VENDOR_ID );
    pci_set_word(pci_conf + PCI_DEVICE_ID,  QAIC_PCI_DEVICE_ID_AIC080 );
    pci_set_word(pci_conf + PCI_CLASS_DEVICE, QAIC_PCI_CLASS_ACCEL );
    pci_set_byte(pci_conf + PCI_REVISION_ID, 0x01);
    pci_config_set_interrupt_pin(pci_conf, 1);

    /* Enable PCIe capability to satisfy pcie_endpoint_cap_init */
    pdev->cap_present |= QEMU_PCI_CAP_EXPRESS;
    pcie_endpoint_cap_init(pdev, 0x80);
    int pm_pos = pci_add_capability(pdev, PCI_CAP_ID_PM, 0, PCI_PM_SIZEOF, errp);
    if (pm_pos > 0) {
        pci_set_word(pci_conf + pm_pos + PCI_PM_PMC, 0x0003); 
    }

    /* BAR Initialization
     * From aic080_config in qaic_drv.c:
     *   .bar_mask = BIT(0) | BIT(2) | BIT(4)
     *   .mhi_bar_idx = 0,
     *   .dbc_bar_idx = 2,
     * The driver uses pci_select_bars(IORESOURCE_MEM) and checks the mask
     * against this configuration. It does not check sizes, so we are free
     * (within the non-hallucination constraint) to choose reasonable sizes
     * for the MMIO regions as long as they are non-zero and power-of-two.
     * QAIC_DBC_BASE and QAIC_DBC_SIZE are defined in qaic_drv.c and used
     * to compute DBC offsets; however, this file only uses these to compute
     * software-visible pointers and never touches the actual MMIO.
     *
     * We therefore create three MMIO BARs with arbitrary but valid sizes.
     * BAR0 and BAR2 are functionally important (MHI and DBC), BAR4 exists
     * but is not used in this fragment.
     */

    s->num_bars = 3;

    s->bar_info[0].index = 0;
    s->bar_info[0].type  = BAR_TYPE_MMIO;
    s->bar_info[0].size  = 1 * MiB; /* MHI BAR, opaque to this file */
    s->bar_info[0].name  = "qaic-bar0-mhi";

    s->bar_info[1].index = 2;
    s->bar_info[1].type  = BAR_TYPE_MMIO;
    s->bar_info[1].size  = QAIC_DBC_BASE + (QAIC_DBC_SIZE * 16);
    s->bar_info[1].name  = "qaic-bar2-dbc";

    s->bar_info[2].index = 4;
    s->bar_info[2].type  = BAR_TYPE_MMIO;
    s->bar_info[2].size  = 1 * MiB;
    s->bar_info[2].name  = "qaic-bar4";

    if (s->num_bars > 0) {
        for (int i = 0; i < s->num_bars; i++) {
            pcibase_register_bar(pdev, s, &s->bar_info[i], errp);
        }
    }

    /*
     * MSI/MSI-X capabilities:
     * The driver calls pci_alloc_irq_vectors(pdev, irq_count, irq_count,
     * PCI_IRQ_MSI | PCI_IRQ_MSIX). QEMU will allocate vectors based on the
     * presence of MSI/MSI-X capabilities. To allow both, we initialize a
     * basic MSI capability; enabling MSIX is optional and not strictly
     * required for the driver's initial probe and bind.
     */

    Error *local_err = NULL;

    /* Initialize MSI with a single vector; the driver may request up to
     * qdev->num_dbc + 1, but QEMU falls back gracefully as long as MSI is
     * present. This satisfies the pci_alloc_irq_vectors call.
     */
    if (msi_init(pdev, 0, 1, true, false, &local_err) == 0) {
        s->has_msi = true;
    } else {
        s->has_msi = false;
        if (local_err) {
            error_propagate(errp, local_err);
        }
    }

    /* We do not create an MSI-X table BAR because the driver only requests
     * MSI/MSIX via the generic API and does not explicitly depend on MSIX.
     */
}

static void pcibase_uninit(PCIDevice *pdev)
{
    PCIBaseState *s = PCIBASE_DEVICE(pdev);
    (void)s;

    if (msix_enabled(pdev)) {
        msix_uninit(pdev, NULL, NULL);
    }
    if (msi_enabled(pdev)) {
        msi_uninit(pdev);
    }
}

/* Minimal VMState to satisfy QEMU migration subsystems */
static const VMStateDescription vmstate_pcibase = {
    .name = "qaic_pci",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_PCI_DEVICE(parent_obj, PCIBaseState),
        VMSTATE_END_OF_LIST()
    }
};

static void pcibase_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    PCIDeviceClass *k = PCI_DEVICE_CLASS(klass);

    k->realize = pcibase_realize;
    k->exit    = pcibase_uninit;
    dc->reset  = pcibase_reset;
    dc->vmsd   = &vmstate_pcibase;
    set_bit(DEVICE_CATEGORY_MISC, dc->categories);
}

static void pcibase_register_types(void)
{
    static InterfaceInfo interfaces[] = {
        { INTERFACE_PCIE_DEVICE },
        { INTERFACE_CONVENTIONAL_PCI_DEVICE },
        { },
    };

    static const TypeInfo pcibase_info = {
        .name = TYPE_PCIBASE_DEVICE,
        .parent = TYPE_PCI_DEVICE,
        .instance_size = sizeof(PCIBaseState),
        .class_init = pcibase_class_init,
        .interfaces = interfaces,
    };

    type_register_static(&pcibase_info);
}

type_init(pcibase_register_types);
