/* QEMU 8.2.10 virtual PCI device for megaraid_sas
   Generated by ai, Phase 3 Repair */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "qemu/module.h"
#include "qemu/timer.h"
#include "qemu/log.h"
#include "qemu/host-utils.h"
#include "qemu/bswap.h"
#include "qapi/error.h"
#include "exec/memory.h"
#include "sysemu/dma.h"
#include "hw/pci/pci.h"
#include "hw/pci/msi.h"
#include "hw/pci/msix.h"
#include "hw/pci/pcie.h"
#include "hw/qdev-properties.h"
#include "hw/qdev-core.h"
#include "migration/vmstate.h"

#define TYPE_PCIBASE_DEVICE "megaraid_sas_pci"
typedef struct PCIBaseState PCIBaseState;
OBJECT_DECLARE_SIMPLE_TYPE(PCIBaseState, PCIBASE_DEVICE)

/* PCI IDs */
#define PCI_VENDOR_ID_LSI_LOGIC  0x1000
#define PCI_DEVICE_ID_LSI_SAS1064R  0x0411

/* Register offsets */
#define MFI_DOORBELL                     0x0000
#define MFI_FUSION_SEQ_OFFSET            0x0004
#define MFI_FUSION_HOST_DIAG             0x0008
#define MFI_RESERVED_01                  0x000C
#define MFI_INBOUND_MSG_0                0x0010
#define MFI_INBOUND_MSG_1                0x0014
#define MFI_OUTBOUND_MSG_0               0x0018
#define MFI_OUTBOUND_MSG_1               0x001C
#define MFI_INBOUND_DOORBELL             0x0020
#define MFI_INBOUND_INTR_STATUS          0x0024
#define MFI_INBOUND_INTR_MASK            0x0028
#define MFI_OUTBOUND_DOORBELL            0x002C
#define MFI_OUTBOUND_INTR_STATUS         0x0030
#define MFI_OUTBOUND_INTR_MASK           0x0034
#define MFI_RESERVED_1_0                 0x0038
#define MFI_INBOUND_QUEUE_PORT           0x0040
#define MFI_OUTBOUND_QUEUE_PORT          0x0044
#define MFI_RESERVED_2                   0x0048
#define MFI_REPLY_POST_HOST_INDEX        0x006C
#define MFI_RESERVED_2_2                 0x0070
#define MFI_OUTBOUND_DOORBELL_CLEAR      0x00A0
#define MFI_RESERVED_3                   0x00A4
#define MFI_OUTBOUND_SCRATCH_PAD_0       0x00B0
#define MFI_OUTBOUND_SCRATCH_PAD_1       0x00B4
#define MFI_OUTBOUND_SCRATCH_PAD_2       0x00B8
#define MFI_OUTBOUND_SCRATCH_PAD_3       0x00BC
#define MFI_INBOUND_LOW_QUEUE_PORT       0x00C0
#define MFI_INBOUND_HIGH_QUEUE_PORT      0x00C4
#define MFI_INBOUND_SINGLE_QUEUE_PORT    0x00C8
#define MFI_HOST_DIAG                    0x00FC
#define MFI_SEQ_OFFSET                   0x0100
#define MFI_INDEX_REGISTERS_BASE         0x0104

/* Firmware states */
#define MFI_STATE_MASK                   0xF0000000
#define MFI_STATE_READY                  0xB0000000
#define MFI_STATE_OPERATIONAL            0xC0000000
#define MFI_STATE_FAULT                  0xF0000000

/* Interrupt bits */
#define MFI_OB_INTR_STATUS_MASK         0x00000001
#define MFI_XSCALE_OMR0_CHANGE_INTERRUPT 0x00000002

/* Frame size */
#define MFI_FRAME_SIZE                   64

/* Missing defines – will be provided by Phase 3 */
#define MFI_CMD_INIT       0x06   /* placeholder, will be corrected */
#define MFI_CMD_DCMD       0x03   /* placeholder */
#define MFI_STAT_OK        0x00   /* placeholder */
#define MR_DCMD_CTRL_GET_INFO 0x01010000 /* placeholder */

/* Forward declarations */
static void pcibase_update_irq(PCIBaseState *s);
static void process_inbound_command(PCIBaseState *s, uint64_t val);

struct PCIBaseState {
    PCIDevice parent_obj;

    MemoryRegion bar_regions[6];
    int num_bars;

    bool has_msi;
    bool has_msix;
    uint32_t intr_status; /* inbound interrupt status */
    uint32_t intr_mask;   /* inbound interrupt mask */

    uint32_t regs[0x1000 / 4];

    /* Init command data */
    dma_addr_t reply_queue_phys;
    dma_addr_t producer_phys;
    dma_addr_t consumer_phys;
    uint32_t max_fw_cmds;
    bool init_received;

    /* Fake controller info */
    uint8_t ctrl_info[4096];
};

/* MMIO/PIO handlers */
static uint64_t pcibase_mmio_read(void *opaque, hwaddr addr, unsigned size)
{
    PCIBaseState *s = opaque;
    uint64_t val = 0;
    uint32_t idx = addr >> 2;

    if (addr >= 0x1000 || size != 4) {
        return 0xFFFFFFFF;
    }

    val = s->regs[idx];
    return val;
}

static void pcibase_mmio_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
    PCIBaseState *s = opaque;
    uint32_t idx = addr >> 2;

    if (addr >= 0x1000 || size != 4) {
        return;
    }

    switch (addr) {
    case MFI_INBOUND_QUEUE_PORT:
        process_inbound_command(s, val);
        break;
    case MFI_OUTBOUND_INTR_STATUS:
        /* Write-1-to-clear */
        s->regs[idx] &= ~val;
        pcibase_update_irq(s);
        break;
    case MFI_OUTBOUND_INTR_MASK:
        s->regs[idx] = val;
        pcibase_update_irq(s);
        break;
    default:
        s->regs[idx] = val;
        break;
    }
}

static const MemoryRegionOps pcibase_mmio_ops = {
    .read = pcibase_mmio_read,
    .write = pcibase_mmio_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = { .min_access_size = 1, .max_access_size = 4 },
    .impl  = { .min_access_size = 1, .max_access_size = 4 },
};

static void pcibase_update_irq(PCIBaseState *s)
{
    PCIDevice *pdev = PCI_DEVICE(s);
    uint32_t status = s->regs[MFI_OUTBOUND_INTR_STATUS >> 2];
    uint32_t mask = s->regs[MFI_OUTBOUND_INTR_MASK >> 2];

    if (status & ~mask) {
        if (msix_enabled(pdev)) {
            msix_notify(pdev, 0);
        } else {
            pci_set_irq(pdev, 1);
        }
    } else {
        if (!msix_enabled(pdev)) {
            pci_set_irq(pdev, 0);
        }
    }
}

static void process_inbound_command(PCIBaseState *s, uint64_t val)
{
    PCIDevice *pdev = PCI_DEVICE(s);
    uint32_t v = (uint32_t)val;
    dma_addr_t frame_phys = (v & 0xFFFFFFF8ULL) << 3;
    uint8_t frame[MFI_FRAME_SIZE];
    uint8_t cmd;
    uint32_t opcode, context;

    pci_dma_read(pdev, frame_phys, frame, MFI_FRAME_SIZE);

    cmd = frame[0];
    context = ldl_le_p(frame + 0x08);

    if (cmd == MFI_CMD_INIT) {
        /* Store reply queue info from the extended area at +64 */
        uint8_t qi[32]; /* struct megasas_init_queue_info size */
        pci_dma_read(pdev, frame_phys + 64, qi, sizeof(qi));

        s->reply_queue_phys = ldl_le_p(qi + 0) | ((uint64_t)ldl_le_p(qi + 4) << 32);
        s->producer_phys = ldl_le_p(qi + 8) | ((uint64_t)ldl_le_p(qi + 12) << 32);
        s->consumer_phys = ldl_le_p(qi + 16) | ((uint64_t)ldl_le_p(qi + 20) << 32);
        s->max_fw_cmds = ldl_le_p(qi + 24) - 1;
        s->init_received = true;

        frame[2] = MFI_STAT_OK; /* cmd_status */
        pci_dma_write(pdev, frame_phys, frame, MFI_FRAME_SIZE);
        /* No interrupt for init (polled) */
    } else {
        /* Other commands: set status OK and post completion */
        frame[2] = MFI_STAT_OK;

        if (cmd == MFI_CMD_DCMD) {
            opcode = ldl_le_p(frame + 0x18);
            if (opcode == MR_DCMD_CTRL_GET_INFO) {
                /* Write fake controller info to data buffer */
                uint8_t sge_count = frame[7];
                if (sge_count > 0) {
                    uint32_t phys_lo = ldl_le_p(frame + 0x2C);
                    uint32_t len = ldl_le_p(frame + 0x30);
                    dma_addr_t data_phys = phys_lo; /* 32-bit address */
                    if (len > sizeof(s->ctrl_info))
                        len = sizeof(s->ctrl_info);
                    pci_dma_write(pdev, data_phys, s->ctrl_info, len);
                }
            }
        }

        pci_dma_write(pdev, frame_phys, frame, MFI_FRAME_SIZE);

        /* Post completion to reply queue */
        if (s->init_received) {
            uint32_t producer, new_producer;
            pci_dma_read(pdev, s->producer_phys, &producer, sizeof(producer));
            producer = le32_to_cpu(producer);

            uint32_t reply_queue_entry = cpu_to_le32(context);
            dma_addr_t addr = s->reply_queue_phys + producer * sizeof(uint32_t);
            pci_dma_write(pdev, addr, &reply_queue_entry, sizeof(reply_queue_entry));

            new_producer = (producer + 1) % (s->max_fw_cmds + 1);
            producer = cpu_to_le32(new_producer);
            pci_dma_write(pdev, s->producer_phys, &producer, sizeof(producer));
        }

        /* Signal interrupt */
        s->regs[MFI_OUTBOUND_INTR_STATUS >> 2] |= MFI_OB_INTR_STATUS_MASK;
        pcibase_update_irq(s);
    }
}

static void pcibase_reset(DeviceState *dev)
{
    PCIBaseState *s = PCIBASE_DEVICE(dev);
    pci_device_reset(PCI_DEVICE(dev));

    memset(s->regs, 0, sizeof(s->regs));
    s->regs[MFI_OUTBOUND_MSG_0 >> 2] = 0xB43C0080; /* Ready state, max_cmds=128, sge=60, MSIX bit */
    s->regs[MFI_OUTBOUND_INTR_MASK >> 2] = 0xFFFFFFFF; /* all masked */
    s->init_received = false;
    memset(s->ctrl_info, 0, sizeof(s->ctrl_info));
    /* Optionally fill ctrl_info with minimal valid data */
}

static void pcibase_realize(PCIDevice *pdev, Error **errp)
{
    PCIBaseState *s = PCIBASE_DEVICE(pdev);
    uint8_t *pci_conf = pdev->config;

    pci_set_word(pci_conf + PCI_VENDOR_ID,  PCI_VENDOR_ID_LSI_LOGIC);
    pci_set_word(pci_conf + PCI_DEVICE_ID,  PCI_DEVICE_ID_LSI_SAS1064R);
    pci_set_word(pci_conf + PCI_CLASS_DEVICE, 0x0104);
    pci_set_byte(pci_conf + PCI_REVISION_ID, 0x01);
    pci_config_set_interrupt_pin(pci_conf, 1);

    pdev->cap_present |= QEMU_PCI_CAP_EXPRESS;
    pcie_endpoint_cap_init(pdev, 0x80);
    int pm_pos = pci_add_capability(pdev, PCI_CAP_ID_PM, 0, PCI_PM_SIZEOF, errp);
    if (pm_pos > 0) {
        pci_set_word(pci_conf + pm_pos + PCI_PM_PMC, 0x0003);
    }

    /* BAR 0: registers */
    memory_region_init_io(&s->bar_regions[0], OBJECT(s), &pcibase_mmio_ops, s, "regs", 0x1000);
    pci_register_bar(pdev, 0, PCI_BASE_ADDRESS_SPACE_MEMORY, &s->bar_regions[0]);

    /* BAR 1: MSI-X */
    memory_region_init_ram(&s->bar_regions[1], OBJECT(s), "msix", 4096, errp);
    pci_register_bar(pdev, 1, PCI_BASE_ADDRESS_SPACE_MEMORY, &s->bar_regions[1]);
    if (msix_init(pdev, 1, &s->bar_regions[1], 1, 0, &s->bar_regions[1], 1, 0x1000, 0, errp)) {
        error_setg(errp, "msix_init failed");
        return;
    }
    s->has_msix = true;

    /* Initialize registers */
    pcibase_reset(DEVICE(s));
}

static void pcibase_uninit(PCIDevice *pdev)
{
    if (msix_enabled(pdev)) {
        msix_uninit(pdev, NULL, NULL);
    }
    if (msi_enabled(pdev)) {
        msi_uninit(pdev);
    }
}

static const VMStateDescription vmstate_pcibase = {
    .name = "megaraid_sas_pci",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_PCI_DEVICE(parent_obj, PCIBaseState),
        VMSTATE_END_OF_LIST()
    }
};

static void pcibase_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    PCIDeviceClass *k = PCI_DEVICE_CLASS(klass);

    k->realize = pcibase_realize;
    k->exit    = pcibase_uninit;
    dc->reset  = pcibase_reset;
    dc->vmsd   = &vmstate_pcibase;
    set_bit(DEVICE_CATEGORY_MISC, dc->categories);
}

static void pcibase_register_types(void)
{
    static InterfaceInfo interfaces[] = {
        { INTERFACE_PCIE_DEVICE },
        { INTERFACE_CONVENTIONAL_PCI_DEVICE },
        { },
    };

    static const TypeInfo pcibase_info = {
        .name = TYPE_PCIBASE_DEVICE,
        .parent = TYPE_PCI_DEVICE,
        .instance_size = sizeof(PCIBaseState),
        .class_init = pcibase_class_init,
        .interfaces = interfaces,
    };

    type_register_static(&pcibase_info);
}

type_init(pcibase_register_types)
