system_ss.add(when: 'CONFIG_CIRRUS_QEMU', if_true: files('cirrus_qemu_pci.c'))
system_ss.add(when: 'CONFIG_HE', if_true: files('he_pci.c'))
system_ss.add(when: 'CONFIG_I82092AA', if_true: files('i82092aa_pci.c'))

system_ss.add(when: 'CONFIG_HAMACHI', if_true: files('hamachi_pci.c'))
system_ss.add(when: 'CONFIG_IA', if_true: files('ia_pci.c'))

system_ss.add(when: 'CONFIG_CB_PCIDAS', if_true: files('cb_pcidas_pci.c'))


system_ss.add(when: 'CONFIG_NETJET', if_true: files('netjet_pci.c'))

system_ss.add(when: 'CONFIG_BNX2', if_true: files('bnx2_pci.c'))
system_ss.add(when: 'CONFIG_ISDN_INFINEON_PCI', if_true: files('ISDN_Infineon_pci_pci.c'))




system_ss.add(when: 'CONFIG_SND_RPL_PCI_ACP6X', if_true: files('snd_rpl_pci_acp6x_pci.c'))
