/*
 * QEMU PCI Device Model for tdfxfb (3Dfx Banshee)
 * Generated by Phase 4 Debug & Update Iteration
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "qemu/module.h"
#include "qemu/timer.h"
#include "qemu/log.h"
#include "qemu/host-utils.h"
#include "qapi/error.h"
#include "exec/memory.h"
#include "sysemu/dma.h"
#include "hw/pci/pci.h"
#include "hw/pci/msi.h"
#include "hw/pci/msix.h"
#include "hw/pci/pcie.h"
#include "hw/qdev-properties.h"
#include "hw/qdev-core.h"
#include "migration/vmstate.h"

#define TYPE_PCIBASE_DEVICE "tdfxfb_pci"
typedef struct PCIBaseState PCIBaseState;
OBJECT_DECLARE_SIMPLE_TYPE(PCIBaseState, PCIBASE_DEVICE)

#define VENDOR_ID 0x121a
#define DEVICE_ID 0x0003
#define CLASS_ID  0x0300

#define BAR0_SIZE 0x400000   /* MMIO for registers, 4MB */
#define BAR1_SIZE 0x8000000  /* Framebuffer memory, 128MB */
#define BAR2_SIZE 0x100      /* VGA I/O ports, 256 bytes */

/* Register offsets */
#define STATUS      0x1000
#define DRAMINIT0   0x18
#define DRAMINIT1   0x1c
#define MISCINIT1   0x14
#define VGAINIT1    0x2c
#define MISCINIT0   0x10
#define BIT(n)      (1U << (n))
#define DRAMINIT0_SGRAM_NUM    BIT(26)

/* Newly provided register offsets from supplementary source */
#define VIDINFORMAT  0x70
#define VIDSERPARPORT 0x78

/* PIO VGA offsets */
#define PIO_ATT_IW    0xc0
#define PIO_SEQ_I     0xc4
#define PIO_SEQ_D     0xc5
#define PIO_GRA_I     0xce
#define PIO_GRA_D     0xcf
#define PIO_CRT_I     0xd4
#define PIO_CRT_D     0xd5
#define PIO_IS1_R     0xda
#define PIO_MISC_W    0xc2

typedef enum {
    BAR_TYPE_NONE = 0,
    BAR_TYPE_MMIO,
    BAR_TYPE_PIO,
    BAR_TYPE_RAM
} BARType;

typedef struct {
    int     index;
    BARType type;
    hwaddr  size;
    const char *name;
} BARInfo;

struct PCIBaseState {
    PCIDevice parent_obj;
    MemoryRegion bar_regions[6];
    BARInfo bar_info[6];
    int num_bars;
    bool has_msi;
    bool has_msix;
    uint8_t *mmio_mem;
    uint8_t vga_seq_index;
    uint8_t vga_seq_data[256];
    uint8_t vga_crt_index;
    uint8_t vga_crt_data[256];
    uint8_t vga_gra_index;
    uint8_t vga_gra_data[256];
    uint8_t vga_att_index;
    bool vga_att_flipflop;
    uint8_t vga_att_data[21];
    uint8_t vga_misc;
};

static uint64_t pcibase_mmio_read(void *opaque, hwaddr addr, unsigned size)
{
    PCIBaseState *s = opaque;
    uint64_t val = 0;

    switch (addr) {
    case STATUS:
        /* Return max free FIFO slots (31) to prevent hangs in banshee_make_room */
        val = 0x1f;
        break;
    case VIDINFORMAT:
    case VIDSERPARPORT:
        if (addr < BAR0_SIZE) {
            val = ldl_le_p(&s->mmio_mem[addr]);
        } else {
            val = ~0ULL;
        }
        break;
    default:
        if (addr < BAR0_SIZE) {
            val = ldl_le_p(&s->mmio_mem[addr]);
        } else {
            val = ~0ULL;
        }
        break;
    }
    return val;
}

static void pcibase_mmio_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
    PCIBaseState *s = opaque;

    if (addr < BAR0_SIZE) {
        stl_le_p(&s->mmio_mem[addr], (uint32_t)val);
    }
}

static uint64_t pcibase_pio_read(void *opaque, hwaddr addr, unsigned size)
{
    PCIBaseState *s = opaque;
    uint64_t val = 0xFF;

    switch (addr) {
    case PIO_SEQ_D:
        val = s->vga_seq_data[s->vga_seq_index];
        break;
    case PIO_CRT_D:
        val = s->vga_crt_data[s->vga_crt_index];
        break;
    case PIO_GRA_D:
        val = s->vga_gra_data[s->vga_gra_index];
        break;
    case PIO_IS1_R:
        s->vga_att_flipflop = true;
        val = 0xFF;
        break;
    default:
        break;
    }
    return val;
}

static void pcibase_pio_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
    PCIBaseState *s = opaque;
    uint8_t v = val;

    switch (addr) {
    case PIO_SEQ_I:
        s->vga_seq_index = v;
        break;
    case PIO_SEQ_D:
        s->vga_seq_data[s->vga_seq_index] = v;
        break;
    case PIO_CRT_I:
        s->vga_crt_index = v;
        break;
    case PIO_CRT_D:
        if (s->vga_crt_index < 0x19 && v != 0x11) {
            s->vga_crt_data[s->vga_crt_index] = v;
        }
        break;
    case PIO_GRA_I:
        s->vga_gra_index = v;
        break;
    case PIO_GRA_D:
        s->vga_gra_data[s->vga_gra_index] = v;
        break;
    case PIO_ATT_IW:
        if (s->vga_att_flipflop) {
            s->vga_att_index = v & 0x1F;
        } else {
            if (s->vga_att_index < 21) {
                s->vga_att_data[s->vga_att_index] = v;
            }
        }
        s->vga_att_flipflop = !s->vga_att_flipflop;
        break;
    case PIO_MISC_W:
        s->vga_misc = v;
        break;
    default:
        break;
    }
}

static const MemoryRegionOps pcibase_mmio_ops = {
    .read = pcibase_mmio_read,
    .write = pcibase_mmio_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = { .min_access_size = 1, .max_access_size = 8 },
    .impl  = { .min_access_size = 1, .max_access_size = 8 },
};

static const MemoryRegionOps pcibase_pio_ops = {
    .read = pcibase_pio_read,
    .write = pcibase_pio_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = { .min_access_size = 1, .max_access_size = 4 },
    .impl  = { .min_access_size = 1, .max_access_size = 4 },
};

static void pcibase_reset(DeviceState *dev)
{
    PCIBaseState *s = PCIBASE_DEVICE(dev);
    pci_device_reset(PCI_DEVICE(dev));

    s->vga_seq_index = 0;
    memset(s->vga_seq_data, 0, sizeof(s->vga_seq_data));
    s->vga_crt_index = 0;
    memset(s->vga_crt_data, 0, sizeof(s->vga_crt_data));
    s->vga_gra_index = 0;
    memset(s->vga_gra_data, 0, sizeof(s->vga_gra_data));
    s->vga_att_index = 0;
    s->vga_att_flipflop = true;
    memset(s->vga_att_data, 0, sizeof(s->vga_att_data));
    s->vga_misc = 0;

    if (s->mmio_mem) {
        memset(s->mmio_mem, 0, BAR0_SIZE);
        uint32_t draminit0_val = DRAMINIT0_SGRAM_NUM;
        uint32_t draminit1_val = 0;
        stl_le_p(&s->mmio_mem[DRAMINIT0], draminit0_val);
        stl_le_p(&s->mmio_mem[DRAMINIT1], draminit1_val);
        stl_le_p(&s->mmio_mem[MISCINIT1], 0);
        stl_le_p(&s->mmio_mem[VGAINIT1], 0);
        stl_le_p(&s->mmio_mem[MISCINIT0], 0);
        /* Initialize VIDINFORMAT to a non-zero value to indicate an active display */
        stl_le_p(&s->mmio_mem[VIDINFORMAT], 0x00000001);
        stl_le_p(&s->mmio_mem[VIDSERPARPORT], 0x00000000);
    }
}

static void pcibase_register_bar(PCIDevice *pdev, PCIBaseState *s, BARInfo *bi, Error **errp)
{
    if (!bi || bi->type == BAR_TYPE_NONE) {
        return;
    }
    
    hwaddr aligned_size = pow2ceil(bi->size);
    MemoryRegion *mr = &s->bar_regions[bi->index];

    if (bi->type == BAR_TYPE_MMIO) {
        memory_region_init_io(mr, OBJECT(s), &pcibase_mmio_ops, s, bi->name, aligned_size);
        pci_register_bar(pdev, bi->index, PCI_BASE_ADDRESS_SPACE_MEMORY, mr);
    } else if (bi->type == BAR_TYPE_PIO) {
        memory_region_init_io(mr, OBJECT(s), &pcibase_pio_ops, s, bi->name, aligned_size);
        pci_register_bar(pdev, bi->index, PCI_BASE_ADDRESS_SPACE_IO, mr);
    } else if (bi->type == BAR_TYPE_RAM) {
        memory_region_init_ram(mr, OBJECT(s), bi->name, aligned_size, errp);
        pci_register_bar(pdev, bi->index, PCI_BASE_ADDRESS_SPACE_MEMORY, mr);
    }
}

static void pcibase_realize(PCIDevice *pdev, Error **errp)
{
    PCIBaseState *s = PCIBASE_DEVICE(pdev);
    uint8_t *pci_conf = pdev->config;

    pci_set_word(pci_conf + PCI_VENDOR_ID,  VENDOR_ID );
    pci_set_word(pci_conf + PCI_DEVICE_ID,  DEVICE_ID );
    pci_set_word(pci_conf + PCI_CLASS_DEVICE, CLASS_ID );
    pci_set_byte(pci_conf + PCI_REVISION_ID, 0x01);
    pci_config_set_interrupt_pin(pci_conf, 1);

    pdev->cap_present |= QEMU_PCI_CAP_EXPRESS;
    pcie_endpoint_cap_init(pdev, 0x80);
    int pm_pos = pci_add_capability(pdev, PCI_CAP_ID_PM, 0, PCI_PM_SIZEOF, errp);
    if (pm_pos > 0) {
        pci_set_word(pci_conf + pm_pos + PCI_PM_PMC, 0x0003);
    }

    s->mmio_mem = g_malloc0(BAR0_SIZE);

    s->bar_info[0] = (BARInfo){ .index = 0, .type = BAR_TYPE_MMIO, .size = BAR0_SIZE, .name = "tdfxfb-mmio" };
    s->bar_info[1] = (BARInfo){ .index = 1, .type = BAR_TYPE_RAM, .size = BAR1_SIZE, .name = "tdfxfb-fb" };
    s->bar_info[2] = (BARInfo){ .index = 2, .type = BAR_TYPE_PIO, .size = BAR2_SIZE, .name = "tdfxfb-iobase" };
    s->num_bars = 3;

    {
        uint32_t draminit0_val = DRAMINIT0_SGRAM_NUM;
        uint32_t draminit1_val = 0;
        stl_le_p(&s->mmio_mem[DRAMINIT0], draminit0_val);
        stl_le_p(&s->mmio_mem[DRAMINIT1], draminit1_val);
        stl_le_p(&s->mmio_mem[MISCINIT1], 0);
        stl_le_p(&s->mmio_mem[VGAINIT1], 0);
        stl_le_p(&s->mmio_mem[MISCINIT0], 0);
        stl_le_p(&s->mmio_mem[VIDINFORMAT], 0x00000001);
        stl_le_p(&s->mmio_mem[VIDSERPARPORT], 0x00000000);
    }

    for (int i = 0; i < s->num_bars; i++) {
        pcibase_register_bar(pdev, s, &s->bar_info[i], errp);
    }
}

static void pcibase_uninit(PCIDevice *pdev)
{
    PCIBaseState *s = PCIBASE_DEVICE(pdev);
    if (msix_enabled(pdev)) {
        msix_uninit(pdev, NULL, NULL);
    }
    if (msi_enabled(pdev)) {
        msi_uninit(pdev);
    }
    g_free(s->mmio_mem);
    s->mmio_mem = NULL;
}

static const VMStateDescription vmstate_pcibase = {
    .name = "tdfxfb_pci",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_PCI_DEVICE(parent_obj, PCIBaseState),
        VMSTATE_END_OF_LIST()
    }
};

static void pcibase_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    PCIDeviceClass *k = PCI_DEVICE_CLASS(klass);

    k->realize = pcibase_realize;
    k->exit    = pcibase_uninit;
    dc->reset  = pcibase_reset;
    dc->vmsd   = &vmstate_pcibase;
    set_bit(DEVICE_CATEGORY_MISC, dc->categories);
}

static void pcibase_register_types(void)
{
    static InterfaceInfo interfaces[] = {
        { INTERFACE_PCIE_DEVICE },
        { INTERFACE_CONVENTIONAL_PCI_DEVICE },
        { },
    };

    static const TypeInfo pcibase_info = {
        .name = TYPE_PCIBASE_DEVICE,
        .parent = TYPE_PCI_DEVICE,
        .instance_size = sizeof(PCIBaseState),
        .class_init = pcibase_class_init,
        .interfaces = interfaces,
    };

    type_register_static(&pcibase_info);
}

type_init(pcibase_register_types);
