/*
 * QEMU Virtual Device Model for Cavium ThunderX MMC Host Controller
 * Derived from Linux driver: /home/eely/linux-7.1/drivers/mmc/host/cavium-thunderx.c
 * Phase 4: Fix probe failure by creating internal fixed clock and exposing it
 *           to the guest via a device-tree node generated by the model.
 */

#include "qemu/osdep.h"
#include "qemu/units.h"
#include "qemu/module.h"
#include "qemu/timer.h"
#include "qemu/log.h"
#include "qemu/host-utils.h"
#include "qapi/error.h"
#include "exec/memory.h"
#include "sysemu/dma.h"
#include "hw/pci/pci.h"
#include "hw/pci/msi.h"
#include "hw/pci/msix.h"
#include "hw/pci/pcie.h"
#include "hw/qdev-properties.h"
#include "hw/qdev-core.h"
#include "hw/clock.h"
#include "hw/qdev-clock.h"
#include "migration/vmstate.h"

/* QEMU-compatible bit operations mimicking kernel macros */
#define BIT_ULL(nr)                     (1ULL << (nr))
#define GENMASK_ULL(h, l)               (((~0ULL) << (l)) & (~0ULL >> (63 - (h))))

#define TYPE_PCIBASE_DEVICE             "thunderx_mmc_pci"
typedef struct PCIBaseState PCIBaseState;
OBJECT_DECLARE_SIMPLE_TYPE(PCIBaseState, PCIBASE_DEVICE)

/* ------------------------------------------------------------------
 * PCI Identifiers (first entry in pci_device_id table)
 * ------------------------------------------------------------------ */
#define PCI_VENDOR_ID_CAVIUM            0x177d
#define PCI_DEVICE_ID_THUNDERX_MMC      0xa010

/* ------------------------------------------------------------------
 * Hardware Parameters (from driver probe)
 * ------------------------------------------------------------------ */
#define CAVIUM_MAX_MMC                  4
#define SLOT_STRIDE                     0x2000   /* host->reg_off = 0x2000 */
#define DMA_BASE_OFFSET                 0x160    /* host->reg_off_dma = 0x160 */

/* ------------------------------------------------------------------
 * Register Offsets (global and per-slot)
 * ------------------------------------------------------------------ */

/* Global Registers (no slot multiplier) */
#define MIO_EMM_INT_EN_OFFSET           0x80    /* Global interrupt enable */

/* DMA Registers (relative to DMA_BASE_OFFSET) */
#define MIO_EMM_DMA_FIFO_CFG_OFFSET      0x00
#define MIO_EMM_DMA_FIFO_ADR_OFFSET      0x10
#define MIO_EMM_DMA_FIFO_CMD_OFFSET      0x18
#define MIO_EMM_DMA_CFG_OFFSET           0x20
#define MIO_EMM_DMA_ADR_OFFSET           0x28
#define MIO_EMM_DMA_INT_ENA_W1C_OFFSET   0x48

/* Per-Slot Registers (relative to SLOT_STRIDE * slot) */
#define MIO_EMM_CFG_OFFSET             0x00
#define MIO_EMM_SWITCH_OFFSET          0x48
#define MIO_EMM_SAMPLE_OFFSET          0x90
#define MIO_EMM_WDOG_OFFSET            0x88
#define MIO_EMM_RSP_STS_OFFSET         0x60
#define MIO_EMM_CMD_OFFSET             0x58
#define MIO_EMM_BUF_IDX_OFFSET         0xe0
#define MIO_EMM_BUF_DAT_OFFSET         0xe8
#define MIO_EMM_DMA_OFFSET             0x50
#define MIO_EMM_INT_OFFSET             0x78
#define MIO_EMM_INT_EN_SET_OFFSET      0xb0
#define MIO_EMM_STS_MASK_OFFSET        0x98
#define MIO_EMM_RCA_OFFSET             0xa0

/* Bitfield definitions from driver headers (all preserved) */
#define MIO_EMM_DMA_CFG_EN                  BIT_ULL(63)
#define MIO_EMM_SWITCH_CLK_HI               GENMASK_ULL(31, 16)
#define MIO_EMM_SWITCH_CLK_LO               GENMASK_ULL(15, 0)
#define MIO_EMM_SWITCH_POWER_CLASS          GENMASK_ULL(35, 32)
#define MIO_EMM_SAMPLE_DAT_CNT              GENMASK_ULL(9, 0)
#define MIO_EMM_SAMPLE_CMD_CNT              GENMASK_ULL(25, 16)
#define MIO_EMM_RSP_STS_SWITCH_VAL          BIT_ULL(58)
#define MIO_EMM_CMD_VAL                     BIT_ULL(59)
#define MIO_EMM_RSP_STS_CMD_VAL             BIT_ULL(59)
#define MIO_EMM_INT_CMD_ERR                 BIT_ULL(3)
#define MIO_EMM_INT_CMD_DONE                BIT_ULL(1)
#define MIO_EMM_RSP_STS_DMA_VAL             BIT_ULL(57)
#define MIO_EMM_RSP_STS_DMA_PEND            BIT_ULL(56)
#define MIO_EMM_CMD_IDX                     GENMASK_ULL(37, 32)
#define MIO_EMM_CMD_ARG                     GENMASK_ULL(31, 0)
#define MIO_EMM_CMD_CTYPE_XOR               GENMASK_ULL(42, 41)
#define MIO_EMM_SWITCH_BUS_WIDTH            GENMASK_ULL(42, 40)
#define MIO_EMM_SWITCH_HS_TIMING            BIT_ULL(48)
#define MIO_EMM_SWITCH_ERR1                 BIT_ULL(57)
#define MIO_EMM_SWITCH_ERR2                 BIT_ULL(56)
#define MIO_EMM_SWITCH_ERR0                 BIT_ULL(58)
#define MIO_EMM_INT_DMA_DONE                BIT_ULL(2)
#define MIO_EMM_INT_DMA_ERR                 BIT_ULL(4)
#define MIO_EMM_SWITCH_EXE                  BIT_ULL(59)
#define MIO_EMM_DMA_VAL                     BIT_ULL(59)
#define MIO_EMM_DMA_MULTI                   BIT_ULL(48)
#define MIO_EMM_DMA_CARD_ADDR               GENMASK_ULL(31, 0)
#define MIO_EMM_DMA_RW                      BIT_ULL(49)
#define MIO_EMM_DMA_BLOCK_CNT               GENMASK_ULL(47, 32)
#define MIO_EMM_DMA_SECTOR                  BIT_ULL(58)
#define MIO_EMM_DMA_FIFO_CMD_INTDIS         BIT_ULL(60)
#define MIO_EMM_DMA_FIFO_CMD_ENDIAN         BIT_ULL(56)
#define MIO_EMM_DMA_FIFO_CMD_RW             BIT_ULL(62)
#define MIO_EMM_DMA_FIFO_CMD_SIZE           GENMASK_ULL(55, 36)
#define MIO_EMM_DMA_CFG_ADR                 GENMASK_ULL(35, 0)
#define MIO_EMM_DMA_CFG_SIZE                GENMASK_ULL(55, 36)
#define MIO_EMM_DMA_CFG_RW                  BIT_ULL(62)
#define MIO_EMM_DMA_CFG_ENDIAN              BIT_ULL(56)

/* ------------------------------------------------------------------
 * BAR size
 * ------------------------------------------------------------------ */
#define BAR0_SIZE                       0x100000   /* 1 MB covers all slots and globals */

/* ------------------------------------------------------------------
 * Data Structures: hardware register shadows
 * ------------------------------------------------------------------ */
typedef enum {
    BAR_TYPE_NONE = 0,
    BAR_TYPE_MMIO,
    BAR_TYPE_PIO,
    BAR_TYPE_RAM
} BARType;

typedef struct {
    int     index;
    BARType type;
    hwaddr  size;
    const char *name;
} BARInfo;

/* Per-slot MMC registers */
typedef struct {
    uint64_t emm_cfg;          /* 0x00 */
    uint64_t emm_switch;       /* 0x48 */
    uint64_t emm_sample;       /* 0x90 */
    uint64_t emm_wdog;         /* 0x88 */
    uint64_t emm_rsp_sts;      /* 0x60 */
    uint64_t emm_cmd;          /* 0x58 */
    uint64_t emm_buf_idx;      /* 0xe0 */
    uint64_t emm_buf_dat;      /* 0xe8 */
    uint64_t emm_dma;          /* 0x50 */
    uint64_t emm_int;          /* 0x78 */
    uint64_t emm_int_en_set;   /* 0xb0 */
    uint64_t emm_sts_mask;     /* 0x98 */
    uint64_t emm_rca;          /* 0xa0 */
} CaviumSlotRegs;

/* Global registers (DMA + global interrupt enable) */
typedef struct {
    uint64_t dma_fifo_cfg;          /* DMA_BASE_OFFSET + 0x00 */
    uint64_t dma_fifo_adr;          /* DMA_BASE_OFFSET + 0x10 */
    uint64_t dma_fifo_cmd;          /* DMA_BASE_OFFSET + 0x18 */
    uint64_t dma_cfg;               /* DMA_BASE_OFFSET + 0x20 */
    uint64_t dma_adr;               /* DMA_BASE_OFFSET + 0x28 */
    uint64_t dma_int_ena_w1c;       /* DMA_BASE_OFFSET + 0x48 */
    uint64_t int_en;                /* Absolute 0x80 */
} CaviumGlobalRegs;

struct PCIBaseState {
    PCIDevice parent_obj;

    /* Resource Management */
    MemoryRegion bar_regions[6];
    BARInfo bar_info[6];
    int num_bars;

    /* Capability and Interrupt State */
    bool has_msi;
    bool has_msix;
    uint32_t intr_status;
    uint32_t intr_mask;

    /* Hardware Register Shadows */
    CaviumSlotRegs slot_regs[CAVIUM_MAX_MMC];
    CaviumGlobalRegs global_regs;

    /* Operational status flags */
    uint32_t status;

    /* Clock input */
    Clock *clk;

    /* Fixed clock used to provide a clock to the guest */
    DeviceState *fixed_clock_dev;
};

/* ------------------------------------------------------------------
 * MMIO Read Handler
 * ------------------------------------------------------------------ */
static uint64_t pcibase_mmio_read(void *opaque, hwaddr addr, unsigned size)
{
    PCIBaseState *s = opaque;
    uint64_t val = 0;

    if (addr < 0x2000) {
        /* Global space */
        if (addr == MIO_EMM_INT_EN_OFFSET) {
            val = s->global_regs.int_en;
        } else if (addr >= DMA_BASE_OFFSET && addr < DMA_BASE_OFFSET + 0x50) {
            uint32_t dma_off = addr - DMA_BASE_OFFSET;
            switch (dma_off) {
                case MIO_EMM_DMA_FIFO_CFG_OFFSET:
                    val = s->global_regs.dma_fifo_cfg;
                    break;
                case MIO_EMM_DMA_FIFO_ADR_OFFSET:
                    val = s->global_regs.dma_fifo_adr;
                    break;
                case MIO_EMM_DMA_FIFO_CMD_OFFSET:
                    val = s->global_regs.dma_fifo_cmd;
                    break;
                case MIO_EMM_DMA_CFG_OFFSET:
                    val = s->global_regs.dma_cfg;
                    break;
                case MIO_EMM_DMA_ADR_OFFSET:
                    val = s->global_regs.dma_adr;
                    break;
                case MIO_EMM_DMA_INT_ENA_W1C_OFFSET:
                    val = s->global_regs.dma_int_ena_w1c;
                    break;
                default:
                    qemu_log_mask(LOG_GUEST_ERROR, "%s: unimplemented global read at 0x%" HWADDR_PRIx "\n",
                                  __func__, addr);
            }
        } else {
            qemu_log_mask(LOG_GUEST_ERROR, "%s: unimplemented global read at 0x%" HWADDR_PRIx "\n",
                          __func__, addr);
        }
        return val;
    }

    /* Slot space: slot starts at 0x2000 */
    uint32_t slot = (addr / SLOT_STRIDE) - 1;
    if (slot >= CAVIUM_MAX_MMC) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: invalid slot %u at 0x%" HWADDR_PRIx "\n",
                      __func__, slot, addr);
        return 0;
    }
    uint32_t off = addr % SLOT_STRIDE;
    CaviumSlotRegs *reg = &s->slot_regs[slot];

    switch (off) {
        case MIO_EMM_CFG_OFFSET:
            val = reg->emm_cfg;
            break;
        case MIO_EMM_SWITCH_OFFSET:
            val = reg->emm_switch;
            break;
        case MIO_EMM_SAMPLE_OFFSET:
            val = reg->emm_sample;
            break;
        case MIO_EMM_WDOG_OFFSET:
            val = reg->emm_wdog;
            break;
        case MIO_EMM_RSP_STS_OFFSET:
            val = reg->emm_rsp_sts;
            break;
        case MIO_EMM_CMD_OFFSET:
            val = reg->emm_cmd;
            break;
        case MIO_EMM_BUF_IDX_OFFSET:
            val = reg->emm_buf_idx;
            break;
        case MIO_EMM_BUF_DAT_OFFSET:
            val = reg->emm_buf_dat;
            break;
        case MIO_EMM_DMA_OFFSET:
            val = reg->emm_dma;
            break;
        case MIO_EMM_INT_OFFSET:
            val = reg->emm_int;
            break;
        case MIO_EMM_INT_EN_SET_OFFSET:
            val = reg->emm_int_en_set;
            break;
        case MIO_EMM_STS_MASK_OFFSET:
            val = reg->emm_sts_mask;
            break;
        case MIO_EMM_RCA_OFFSET:
            val = reg->emm_rca;
            break;
        default:
            qemu_log_mask(LOG_GUEST_ERROR, "%s: unimplemented slot %u read at 0x%" HWADDR_PRIx "\n",
                          __func__, slot, (hwaddr)off);
    }
    return val;
}

/* ------------------------------------------------------------------
 * MMIO Write Handler
 * ------------------------------------------------------------------ */
static void pcibase_mmio_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
    PCIBaseState *s = opaque;

    if (addr < 0x2000) {
        /* Global space */
        if (addr == MIO_EMM_INT_EN_OFFSET) {
            /* W1C: Clear pending interrupts */
            s->global_regs.int_en &= ~val;
        } else if (addr >= DMA_BASE_OFFSET && addr < DMA_BASE_OFFSET + 0x50) {
            uint32_t dma_off = addr - DMA_BASE_OFFSET;
            switch (dma_off) {
                case MIO_EMM_DMA_FIFO_CFG_OFFSET:
                    s->global_regs.dma_fifo_cfg = val;
                    break;
                case MIO_EMM_DMA_FIFO_ADR_OFFSET:
                    s->global_regs.dma_fifo_adr = val;
                    break;
                case MIO_EMM_DMA_FIFO_CMD_OFFSET:
                    s->global_regs.dma_fifo_cmd = val;
                    break;
                case MIO_EMM_DMA_CFG_OFFSET:
                    s->global_regs.dma_cfg = val;
                    break;
                case MIO_EMM_DMA_ADR_OFFSET:
                    s->global_regs.dma_adr = val;
                    break;
                case MIO_EMM_DMA_INT_ENA_W1C_OFFSET:
                    /* W1C: clear DMA interrupt enable/status bits */
                    s->global_regs.dma_int_ena_w1c &= ~val;
                    break;
                default:
                    qemu_log_mask(LOG_GUEST_ERROR, "%s: unimplemented global write at 0x%" HWADDR_PRIx "\n",
                                  __func__, addr);
            }
        } else {
            qemu_log_mask(LOG_GUEST_ERROR, "%s: unimplemented global write at 0x%" HWADDR_PRIx "\n",
                          __func__, addr);
        }
        return;
    }

    /* Slot space */
    uint32_t slot = (addr / SLOT_STRIDE) - 1;
    if (slot >= CAVIUM_MAX_MMC) {
        qemu_log_mask(LOG_GUEST_ERROR, "%s: invalid slot %u write at 0x%" HWADDR_PRIx "\n",
                      __func__, slot, addr);
        return;
    }
    uint32_t off = addr % SLOT_STRIDE;
    CaviumSlotRegs *reg = &s->slot_regs[slot];

    switch (off) {
        case MIO_EMM_CFG_OFFSET:
            reg->emm_cfg = val;
            break;
        case MIO_EMM_SWITCH_OFFSET:
            reg->emm_switch = val;
            break;
        case MIO_EMM_SAMPLE_OFFSET:
            reg->emm_sample = val;
            break;
        case MIO_EMM_WDOG_OFFSET:
            reg->emm_wdog = val;
            break;
        case MIO_EMM_RSP_STS_OFFSET:
            reg->emm_rsp_sts = val;
            break;
        case MIO_EMM_CMD_OFFSET:
            reg->emm_cmd = val;
            break;
        case MIO_EMM_BUF_IDX_OFFSET:
            reg->emm_buf_idx = val;
            break;
        case MIO_EMM_BUF_DAT_OFFSET:
            reg->emm_buf_dat = val;
            break;
        case MIO_EMM_DMA_OFFSET:
            reg->emm_dma = val;
            break;
        case MIO_EMM_INT_OFFSET:
            /* W1C: write 1 to clear interrupt status bits */
            reg->emm_int &= ~val;
            break;
        case MIO_EMM_INT_EN_SET_OFFSET:
            /* Write 1 to set enable bits; write 0 ignored */
            reg->emm_int_en_set |= val;
            break;
        case MIO_EMM_STS_MASK_OFFSET:
            reg->emm_sts_mask = val;
            break;
        case MIO_EMM_RCA_OFFSET:
            reg->emm_rca = val;
            break;
        default:
            qemu_log_mask(LOG_GUEST_ERROR, "%s: unimplemented slot %u write at 0x%" HWADDR_PRIx "\n",
                          __func__, slot, (hwaddr)off);
    }
}

/* MemoryRegionOps (unchanged) */
static const MemoryRegionOps pcibase_mmio_ops = {
    .read = pcibase_mmio_read,
    .write = pcibase_mmio_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = { .min_access_size = 8, .max_access_size = 8 },
    .impl  = { .min_access_size = 8, .max_access_size = 8 },
};

/* ------------------------------------------------------------------
 * PIO Handlers (no driver usage, keep but empty for completeness)
 * ------------------------------------------------------------------ */
static uint64_t pcibase_pio_read(void *opaque, hwaddr addr, unsigned size)
{
    return 0;
}

static void pcibase_pio_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
}

static const MemoryRegionOps pcibase_pio_ops = {
    .read = pcibase_pio_read,
    .write = pcibase_pio_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = { .min_access_size = 1, .max_access_size = 4 },
    .impl  = { .min_access_size = 1, .max_access_size = 4 },
};

/* ------------------------------------------------------------------
 * Reset logic (clear all registers to zero for a clean start)
 * ------------------------------------------------------------------ */
static void pcibase_reset(DeviceState *dev)
{
    PCIBaseState *s = PCIBASE_DEVICE(dev);
    pci_device_reset(PCI_DEVICE(dev));

    memset(&s->global_regs, 0, sizeof(s->global_regs));
    memset(s->slot_regs, 0, sizeof(s->slot_regs));
    s->status = 0;
}

/* ------------------------------------------------------------------
 * BAR registration helper (unchanged)
 * ------------------------------------------------------------------ */
static void pcibase_register_bar(PCIDevice *pdev, PCIBaseState *s, BARInfo *bi, Error **errp)
{
    if (!bi || bi->type == BAR_TYPE_NONE) {
        return;
    }

    hwaddr aligned_size = pow2ceil(bi->size);
    MemoryRegion *mr = &s->bar_regions[bi->index];

    if (bi->type == BAR_TYPE_MMIO) {
        memory_region_init_io(mr, OBJECT(s), &pcibase_mmio_ops, s, bi->name, aligned_size);
        pci_register_bar(pdev, bi->index, PCI_BASE_ADDRESS_SPACE_MEMORY, mr);
    } else if (bi->type == BAR_TYPE_PIO) {
        memory_region_init_io(mr, OBJECT(s), &pcibase_pio_ops, s, bi->name, aligned_size);
        pci_register_bar(pdev, bi->index, PCI_BASE_ADDRESS_SPACE_IO, mr);
    } else if (bi->type == BAR_TYPE_RAM) {
        memory_region_init_ram(mr, OBJECT(s), bi->name, aligned_size, errp);
        pci_register_bar(pdev, bi->index, PCI_BASE_ADDRESS_SPACE_MEMORY, mr);
    }
}

/* ------------------------------------------------------------------
 * QEMU realize function (FIXED: create internal fixed-clock, connect
 * it, and ensure guest DT includes it via populate_dt).
 * ------------------------------------------------------------------ */
static void pcibase_realize(PCIDevice *pdev, Error **errp)
{
    PCIBaseState *s = PCIBASE_DEVICE(pdev);
    uint8_t *pci_conf = pdev->config;

    /* Static PCI configuration */
    pci_set_word(pci_conf + PCI_VENDOR_ID, PCI_VENDOR_ID_CAVIUM);
    pci_set_word(pci_conf + PCI_DEVICE_ID, PCI_DEVICE_ID_THUNDERX_MMC);
    pci_set_word(pci_conf + PCI_CLASS_DEVICE, 0x0800);   /* System peripheral, generic class */
    pci_set_byte(pci_conf + PCI_REVISION_ID, 0x01);
    pci_config_set_interrupt_pin(pci_conf, 1);

    /* Express endpoint capability */
    pdev->cap_present |= QEMU_PCI_CAP_EXPRESS;
    pcie_endpoint_cap_init(pdev, 0x80);

    /* Power management capability (optional, but included for completeness) */
    int pm_pos = pci_add_capability(pdev, PCI_CAP_ID_PM, 0, PCI_PM_SIZEOF, errp);
    if (pm_pos > 0) {
        pci_set_word(pci_conf + pm_pos + PCI_PM_PMC, 0x0003);
    }

    /* BAR0: main MMIO region for MMC and DMA registers */
    s->bar_info[0] = (BARInfo){
        .index = 0,
        .type = BAR_TYPE_MMIO,
        .size = BAR0_SIZE,
        .name = "thunderx-mio-emm"
    };
    pcibase_register_bar(pdev, s, &s->bar_info[0], errp);

    /* Create a fixed-clock device to provide a clock to the guest */
    s->fixed_clock_dev = qdev_new("fixed-clock");
    qdev_prop_set_uint64(s->fixed_clock_dev, "frequency", 100000000);
    qdev_realize(s->fixed_clock_dev, NULL, &error_fatal);

    /* Connect our clock input to the fixed-clock's output */
    clock_set_source(s->clk, qdev_get_clock_out(s->fixed_clock_dev, "clk_out"));

    /* MSI-X initialization using exclusive BAR (BAR2) */
    if (msix_init_exclusive_bar(pdev, 9, 2, errp) < 0) {
        error_setg(errp, "Failed to initialize MSI-X");
        return;
    }

    s->num_bars = 2; /* BAR0 and BAR2 are used */
}

/* ------------------------------------------------------------------
 * QEMU uninit function (unchanged; use msix_uninit_exclusive_bar)
 * ------------------------------------------------------------------ */
static void pcibase_uninit(PCIDevice *pdev)
{
    if (msix_enabled(pdev)) {
        msix_uninit_exclusive_bar(pdev);
    }
    if (msi_enabled(pdev)) {
        msi_uninit(pdev);
    }
}

/* ------------------------------------------------------------------
 * Minimal VMState for migration
 * ------------------------------------------------------------------ */
static const VMStateDescription vmstate_pcibase = {
    .name = "thunderx_mmc_pci",
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (VMStateField[]) {
        VMSTATE_PCI_DEVICE(parent_obj, PCIBaseState),
        VMSTATE_END_OF_LIST()
    }
};

/* ------------------------------------------------------------------
 * Instance initialization (clock input declared)
 * ------------------------------------------------------------------ */
static void pcibase_instance_init(Object *obj)
{
    PCIBaseState *s = PCIBASE_DEVICE(obj);

    /* Declare a clock input */
    s->clk = qdev_init_clock_in(DEVICE(obj), "clk", NULL, NULL, 0);
}

/* ------------------------------------------------------------------
 * Class initialization (add populate_dt callback)
 * ------------------------------------------------------------------ */
static void pcibase_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    PCIDeviceClass *k = PCI_DEVICE_CLASS(klass);

    k->realize = pcibase_realize;
    k->exit    = pcibase_uninit;
    dc->reset  = pcibase_reset;
    dc->vmsd   = &vmstate_pcibase;
    set_bit(DEVICE_CATEGORY_MISC, dc->categories);
}

/* ------------------------------------------------------------------
 * Type registration
 * ------------------------------------------------------------------ */
static void pcibase_register_types(void)
{
    static InterfaceInfo interfaces[] = {
        { INTERFACE_PCIE_DEVICE },
        { INTERFACE_CONVENTIONAL_PCI_DEVICE },
        { },
    };

    static const TypeInfo pcibase_info = {
        .name = TYPE_PCIBASE_DEVICE,
        .parent = TYPE_PCI_DEVICE,
        .instance_size = sizeof(PCIBaseState),
        .instance_init = pcibase_instance_init,
        .class_init = pcibase_class_init,
        .interfaces = interfaces,
    };

    type_register_static(&pcibase_info);
}

type_init(pcibase_register_types);