system_ss.add(when: 'CONFIG_BNA', if_true: files('bna_pci.c'))
system_ss.add(when: 'CONFIG_BOCHS_DRM', if_true: files('bochs_drm_pci.c'))
system_ss.add(when: 'CONFIG_BT8XXGPIO', if_true: files('bt8xxgpio_pci.c'))
system_ss.add(when: 'CONFIG_BTTV', if_true: files('bttv_pci.c'))
system_ss.add(when: 'CONFIG_C3XXXVF', if_true: files('c3xxxvf_pci.c'))
system_ss.add(when: 'CONFIG_C3XXX', if_true: files('c3xxx_pci.c'))
system_ss.add(when: 'CONFIG_C6XXVF', if_true: files('c6xxvf_pci.c'))
system_ss.add(when: 'CONFIG_C6XX', if_true: files('c6xx_pci.c'))
system_ss.add(when: 'CONFIG_CAFE1000_CCIC', if_true: files('cafe1000_ccic_pci.c'))
system_ss.add(when: 'CONFIG_CARMINEFB', if_true: files('carminefb_pci.c'))
system_ss.add(when: 'CONFIG_CASSINI', if_true: files('cassini_pci.c'))
system_ss.add(when: 'CONFIG_CB710', if_true: files('cb710_pci.c'))
system_ss.add(when: 'CONFIG_CB7210_PCI_DRIVER', if_true: files('cb7210_pci_driver_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIDAS64', if_true: files('cb_pcidas64_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIDAS', if_true: files('cb_pcidas_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIDDA', if_true: files('cb_pcidda_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIMDAS', if_true: files('cb_pcimdas_pci.c'))
system_ss.add(when: 'CONFIG_CB_PCIMDDA', if_true: files('cb_pcimdda_pci.c'))
system_ss.add(when: 'CONFIG_CCP', if_true: files('ccp_pci.c'))
system_ss.add(when: 'CONFIG_CDNS2_PCI', if_true: files('cdns2_pci_pci.c'))
system_ss.add(when: 'CONFIG_CDNS3_PCI_USBSS', if_true: files('cdns3_pci_usbss_pci.c'))
system_ss.add(when: 'CONFIG_CEC_PCI_DRIVER', if_true: files('cec_pci_driver_pci.c'))
system_ss.add(when: 'CONFIG_CIRRUS_QEMU', if_true: files('cirrus_qemu_pci.c'))
system_ss.add(when: 'CONFIG_CI_HDRC_PCI', if_true: files('ci_hdrc_pci_pci.c'))
system_ss.add(when: 'CONFIG_CN10K_RNG', if_true: files('cn10k_rng_pci.c'))
system_ss.add(when: 'CONFIG_CNN55XX', if_true: files('CNN55XX_pci.c'))
system_ss.add(when: 'CONFIG_COM20020', if_true: files('com20020_pci.c'))
system_ss.add(when: 'CONFIG_CONTEC_PCI_DIO', if_true: files('contec_pci_dio_pci.c'))
system_ss.add(when: 'CONFIG_CP500', if_true: files('cp500_pci.c'))
system_ss.add(when: 'CONFIG_CS5535_MFD', if_true: files('cs5535_mfd_pci.c'))
system_ss.add(when: 'CONFIG_CSIOSTOR', if_true: files('csiostor_pci.c'))
system_ss.add(when: 'CONFIG_CX23885', if_true: files('cx23885_pci.c'))
system_ss.add(when: 'CONFIG_CX8800', if_true: files('cx8800_pci.c'))
system_ss.add(when: 'CONFIG_CX88_AUDIO', if_true: files('cx88_audio_pci.c'))
system_ss.add(when: 'CONFIG_MIPI_I3C_HCI_PCI', if_true: files('mipi_i3c_hci_pci_pci.c'))
system_ss.add(when: 'CONFIG_ML_IOH_GPIO', if_true: files('ml_ioh_gpio_pci.c'))
system_ss.add(when: 'CONFIG_MT7615E', if_true: files('mt7615e_pci.c'))
system_ss.add(when: 'CONFIG_MT76X0E', if_true: files('mt76x0e_pci.c'))
system_ss.add(when: 'CONFIG_MTK_T7XX', if_true: files('mtk_t7xx_pci.c'))
system_ss.add(when: 'CONFIG_MWIFIEX_PCIE', if_true: files('mwifiex_pcie_pci.c'))
system_ss.add(when: 'CONFIG_NATSEMI', if_true: files('natsemi_pci.c'))
system_ss.add(when: 'CONFIG_NE2K_PCI', if_true: files('ne2k_pci_pci.c'))
system_ss.add(when: 'CONFIG_NETUP_UNIDVB', if_true: files('netup_unidvb_pci.c'))
system_ss.add(when: 'CONFIG_NFORCE2_SMBUS', if_true: files('nForce2_smbus_pci.c'))
system_ss.add(when: 'CONFIG_NITRO_ENCLAVES', if_true: files('nitro_enclaves_pci.c'))
system_ss.add(when: 'CONFIG_NI_6527', if_true: files('ni_6527_pci.c'))
system_ss.add(when: 'CONFIG_NI_65XX', if_true: files('ni_65xx_pci.c'))
system_ss.add(when: 'CONFIG_NI_660X', if_true: files('ni_660x_pci.c'))
system_ss.add(when: 'CONFIG_NI_670X', if_true: files('ni_670x_pci.c'))
system_ss.add(when: 'CONFIG_NI_PCIDIO', if_true: files('ni_pcidio_pci.c'))
system_ss.add(when: 'CONFIG_NI_PCIMIO', if_true: files('ni_pcimio_pci.c'))
system_ss.add(when: 'CONFIG_NOUVEAU', if_true: files('nouveau_pci.c'))
system_ss.add(when: 'CONFIG_NOZOMI', if_true: files('nozomi_pci.c'))
system_ss.add(when: 'CONFIG_NTB_HW_EPF', if_true: files('ntb_hw_epf_pci.c'))
system_ss.add(when: 'CONFIG_NTB_HW_IDT', if_true: files('ntb_hw_idt_pci.c'))
system_ss.add(when: 'CONFIG_NVIDIA_GPU', if_true: files('nvidia_gpu_pci.c'))
system_ss.add(when: 'CONFIG_OCTEON_EP', if_true: files('octeon_ep_pci.c'))
system_ss.add(when: 'CONFIG_OCTEP_HP', if_true: files('octep_hp_pci.c'))
system_ss.add(when: 'CONFIG_OHCI_PCI', if_true: files('ohci_pci_pci.c'))
system_ss.add(when: 'CONFIG_PARPORT_PC', if_true: files('parport_pc_pci.c'))
system_ss.add(when: 'CONFIG_PARPORT_SERIAL', if_true: files('parport_serial_pci.c'))
system_ss.add(when: 'CONFIG_PATA_ALI', if_true: files('pata_ali_pci.c'))
system_ss.add(when: 'CONFIG_PATA_ARTOP', if_true: files('pata_artop_pci.c'))
system_ss.add(when: 'CONFIG_PATA_ATIIXP', if_true: files('pata_atiixp_pci.c'))
system_ss.add(when: 'CONFIG_PATA_ATP867X', if_true: files('pata_atp867x_pci.c'))
system_ss.add(when: 'CONFIG_PATA_CMD640', if_true: files('pata_cmd640_pci.c'))
system_ss.add(when: 'CONFIG_PATA_CMD64X', if_true: files('pata_cmd64x_pci.c'))
system_ss.add(when: 'CONFIG_PATA_CS5520', if_true: files('pata_cs5520_pci.c'))
system_ss.add(when: 'CONFIG_PATA_CS5535', if_true: files('pata_cs5535_pci.c'))
system_ss.add(when: 'CONFIG_PATA_CS5536', if_true: files('pata_cs5536_pci.c'))
system_ss.add(when: 'CONFIG_PATA_EFAR', if_true: files('pata_efar_pci.c'))
system_ss.add(when: 'CONFIG_PATA_HPT366', if_true: files('pata_hpt366_pci.c'))
system_ss.add(when: 'CONFIG_PATA_HPT37X', if_true: files('pata_hpt37x_pci.c'))
system_ss.add(when: 'CONFIG_PATA_HPT3X2N', if_true: files('pata_hpt3x2n_pci.c'))
system_ss.add(when: 'CONFIG_PATA_HPT3X3', if_true: files('pata_hpt3x3_pci.c'))
system_ss.add(when: 'CONFIG_PATA_IT8213', if_true: files('pata_it8213_pci.c'))
system_ss.add(when: 'CONFIG_PATA_IT821X', if_true: files('pata_it821x_pci.c'))
system_ss.add(when: 'CONFIG_PATA_JMICRON', if_true: files('pata_jmicron_pci.c'))
system_ss.add(when: 'CONFIG_PATA_MARVELL', if_true: files('pata_marvell_pci.c'))
system_ss.add(when: 'CONFIG_PATA_MPIIX', if_true: files('pata_mpiix_pci.c'))
system_ss.add(when: 'CONFIG_PATA_NETCELL', if_true: files('pata_netcell_pci.c'))
system_ss.add(when: 'CONFIG_PATA_NINJA32', if_true: files('pata_ninja32_pci.c'))
system_ss.add(when: 'CONFIG_PATA_NS87410', if_true: files('pata_ns87410_pci.c'))
system_ss.add(when: 'CONFIG_PATA_NS87415', if_true: files('pata_ns87415_pci.c'))
system_ss.add(when: 'CONFIG_PATA_OLDPIIX', if_true: files('pata_oldpiix_pci.c'))
system_ss.add(when: 'CONFIG_PATA_OPTI', if_true: files('pata_opti_pci.c'))
system_ss.add(when: 'CONFIG_PATA_PDC2027X', if_true: files('pata_pdc2027x_pci.c'))
system_ss.add(when: 'CONFIG_PATA_PDC202XX_OLD', if_true: files('pata_pdc202xx_old_pci.c'))
system_ss.add(when: 'CONFIG_PATA_PICCOLO', if_true: files('pata_piccolo_pci.c'))
system_ss.add(when: 'CONFIG_PATA_RDC', if_true: files('pata_rdc_pci.c'))
system_ss.add(when: 'CONFIG_PATA_RZ1000', if_true: files('pata_rz1000_pci.c'))
system_ss.add(when: 'CONFIG_PATA_SERVERWORKS', if_true: files('pata_serverworks_pci.c'))
system_ss.add(when: 'CONFIG_PATA_SIL680', if_true: files('pata_sil680_pci.c'))
system_ss.add(when: 'CONFIG_PATA_SIS', if_true: files('pata_sis_pci.c'))
system_ss.add(when: 'CONFIG_PATA_SL82C105', if_true: files('pata_sl82c105_pci.c'))
system_ss.add(when: 'CONFIG_PATA_TRIFLEX', if_true: files('pata_triflex_pci.c'))
system_ss.add(when: 'CONFIG_PATA_VIA', if_true: files('pata_via_pci.c'))
system_ss.add(when: 'CONFIG_PC300', if_true: files('PC300_pci.c'))
system_ss.add(when: 'CONFIG_PCH_DMA', if_true: files('pch_dma_pci.c'))
system_ss.add(when: 'CONFIG_PCH_GBE', if_true: files('pch_gbe_pci.c'))
system_ss.add(when: 'CONFIG_PCH_GPIO', if_true: files('pch_gpio_pci.c'))
system_ss.add(when: 'CONFIG_PCH_PHUB', if_true: files('pch_phub_pci.c'))
system_ss.add(when: 'CONFIG_PCH_SPI', if_true: files('pch_spi_pci.c'))
system_ss.add(when: 'CONFIG_PCH_UART', if_true: files('pch_uart_pci.c'))
system_ss.add(when: 'CONFIG_PCI_DAS08', if_true: files('pci_das08_pci.c'))
system_ss.add(when: 'CONFIG_PCI_ENDPOINT_TEST', if_true: files('pci_endpoint_test_pci.c'))

system_ss.add(when: 'CONFIG_PCI_IDIO_16', if_true: files('pci_idio_16_pci.c'))
system_ss.add(when: 'CONFIG_CXGB4VF', if_true: files('cxgb4vf_pci.c'))
system_ss.add(when: 'CONFIG_PCI_PF_STUB', if_true: files('pci_pf_stub_pci.c'))
system_ss.add(when: 'CONFIG_PCI1XXXX_SERIAL', if_true: files('pci1xxxx_serial_pci.c'))
system_ss.add(when: 'CONFIG_PCI1XXXXGP', if_true: files('PCI1xxxxGP_pci.c'))
system_ss.add(when: 'CONFIG_C_CAN_PCI', if_true: files('c_can_pci_pci.c'))
system_ss.add(when: 'CONFIG_PCIE_MP2_AMD', if_true: files('pcie_mp2_amd_pci.c'))
system_ss.add(when: 'CONFIG_PCIPS2', if_true: files('pcips2_pci.c'))
system_ss.add(when: 'CONFIG_DE2104X', if_true: files('de2104x_pci.c'))
system_ss.add(when: 'CONFIG_PCNET32', if_true: files('pcnet32_pci.c'))
system_ss.add(when: 'CONFIG_PCWD_PCI', if_true: files('pcwd_pci_pci.c'))
system_ss.add(when: 'CONFIG_DENALI_NAND_PCI', if_true: files('denali_nand_pci_pci.c'))
system_ss.add(when: 'CONFIG_DFL_PCI', if_true: files('dfl_pci_pci.c'))
system_ss.add(when: 'CONFIG_DH895XCC', if_true: files('dh895xcc_pci.c'))
system_ss.add(when: 'CONFIG_PEAK_PCI', if_true: files('peak_pci_pci.c'))
system_ss.add(when: 'CONFIG_PEAK_PCIEFD', if_true: files('peak_pciefd_pci.c'))
system_ss.add(when: 'CONFIG_PIIX4_SMBUS', if_true: files('piix4_smbus_pci.c'))
system_ss.add(when: 'CONFIG_PLX_DMA', if_true: files('plx_dma_pci.c'))
system_ss.add(when: 'CONFIG_PM80XX', if_true: files('pm80xx_pci.c'))
system_ss.add(when: 'CONFIG_DMFE', if_true: files('dmfe_pci.c'))
system_ss.add(when: 'CONFIG_DT3000', if_true: files('dt3000_pci.c'))
system_ss.add(when: 'CONFIG_DW_EDMA_PCIE', if_true: files('dw_edma_pcie_pci.c'))
system_ss.add(when: 'CONFIG_DW_XDATA_PCIE', if_true: files('dw_xdata_pcie_pci.c'))
system_ss.add(when: 'CONFIG_DWC_XLGMAC', if_true: files('dwc_xlgmac_pci.c'))
system_ss.add(when: 'CONFIG_PTDMA', if_true: files('ptdma_pci.c'))
system_ss.add(when: 'CONFIG_DWC3_HAPS', if_true: files('dwc3_haps_pci.c'))
system_ss.add(when: 'CONFIG_DWC3_PCI', if_true: files('dwc3_pci_pci.c'))
system_ss.add(when: 'CONFIG_PTP_NETC', if_true: files('ptp_netc_pci.c'))
system_ss.add(when: 'CONFIG_DWMAC_LOONGSON_PCI', if_true: files('dwmac_loongson_pci_pci.c'))
system_ss.add(when: 'CONFIG_DWMAC_MOTORCOMM', if_true: files('dwmac_motorcomm_pci.c'))
system_ss.add(when: 'CONFIG_DW_DMAC_PCI', if_true: files('dw_dmac_pci_pci.c'))
system_ss.add(when: 'CONFIG_PVPANIC_PCI', if_true: files('pvpanic_pci_pci.c'))
system_ss.add(when: 'CONFIG_PWM_DWC', if_true: files('pwm_dwc_pci.c'))
system_ss.add(when: 'CONFIG_DW_SPI_PCI', if_true: files('dw_spi_pci_pci.c'))
system_ss.add(when: 'CONFIG_PWM_LPSS', if_true: files('pwm_lpss_pci.c'))
system_ss.add(when: 'CONFIG_DYNA_PCI10XX', if_true: files('dyna_pci10xx_pci.c'))
system_ss.add(when: 'CONFIG_E1000', if_true: files('e1000_pci.c'))
system_ss.add(when: 'CONFIG_E752X_EDAC', if_true: files('e752x_edac_pci.c'))
system_ss.add(when: 'CONFIG_EARTH_PT1', if_true: files('earth_pt1_pci.c'))
system_ss.add(when: 'CONFIG_EC_BHF', if_true: files('ec_bhf_pci.c'))
system_ss.add(when: 'CONFIG_EFA', if_true: files('efa_pci.c'))
system_ss.add(when: 'CONFIG_QLCNIC', if_true: files('qlcnic_pci.c'))
system_ss.add(when: 'CONFIG_QTNFMAC_PCIE', if_true: files('qtnfmac_pcie_pci.c'))
system_ss.add(when: 'CONFIG_EHCI_PCI', if_true: files('ehci_pci_pci.c'))
system_ss.add(when: 'CONFIG_R592', if_true: files('r592_pci.c'))
system_ss.add(when: 'CONFIG_R6040', if_true: files('r6040_pci.c'))
system_ss.add(when: 'CONFIG_EMS_PCI', if_true: files('ems_pci_pci.c'))
system_ss.add(when: 'CONFIG_EMU10K1_GAMEPORT', if_true: files('Emu10k1_gameport_pci.c'))
system_ss.add(when: 'CONFIG_R852', if_true: files('r852_pci.c'))
system_ss.add(when: 'CONFIG_EPIC100', if_true: files('epic100_pci.c'))
system_ss.add(when: 'CONFIG_RADIO_MAXIRADIO', if_true: files('radio_maxiradio_pci.c'))
system_ss.add(when: 'CONFIG_RDC321X_SOUTHBRIDGE', if_true: files('RDC321x_Southbridge_pci.c'))
system_ss.add(when: 'CONFIG_ET131X', if_true: files('et131x_pci.c'))
system_ss.add(when: 'CONFIG_EXAR_SERIAL', if_true: files('exar_serial_pci.c'))
system_ss.add(when: 'CONFIG_RP2', if_true: files('rp2_pci.c'))
system_ss.add(when: 'CONFIG_F81601', if_true: files('f81601_pci.c'))
system_ss.add(when: 'CONFIG_RT2400PCI', if_true: files('rt2400pci_pci.c'))
system_ss.add(when: 'CONFIG_RT2500PCI', if_true: files('rt2500pci_pci.c'))
system_ss.add(when: 'CONFIG_RT61PCI', if_true: files('rt61pci_pci.c'))
system_ss.add(when: 'CONFIG_FEALNX', if_true: files('fealnx_pci.c'))
system_ss.add(when: 'CONFIG_RTL8188EE', if_true: files('rtl8188ee_pci.c'))
system_ss.add(when: 'CONFIG_FM801_GAMEPORT', if_true: files('FM801_gameport_pci.c'))

system_ss.add(when: 'CONFIG_AGPGART_AMD64', if_true: files('agpgart_amd64_pci.c'))
system_ss.add(when: 'CONFIG_ALI1563_SMBUS', if_true: files('ali1563_smbus_pci.c'))
system_ss.add(when: 'CONFIG_AST', if_true: files('ast_pci.c'))
system_ss.add(when: 'CONFIG_ATA_GENERIC', if_true: files('ata_generic_pci.c'))
system_ss.add(when: 'CONFIG_ATA_PIIX', if_true: files('ata_piix_pci.c'))
system_ss.add(when: 'CONFIG_ATL1E', if_true: files('ATL1E_pci.c'))
system_ss.add(when: 'CONFIG_ATOMISP_ISP2', if_true: files('atomisp_isp2_pci.c'))
system_ss.add(when: 'CONFIG_B44', if_true: files('b44_pci.c'))

system_ss.add(when: 'CONFIG_FNIC', if_true: files('fnic_pci.c'))
system_ss.add(when: 'CONFIG_FORCEDETH', if_true: files('forcedeth_pci.c'))
system_ss.add(when: 'CONFIG_RTL8192EE', if_true: files('rtl8192ee_pci.c'))
system_ss.add(when: 'CONFIG_RTL8723AE', if_true: files('rtl8723ae_pci.c'))
system_ss.add(when: 'CONFIG_FSL_ENETC_MDIO', if_true: files('fsl_enetc_mdio_pci.c'))
system_ss.add(when: 'CONFIG_RTL8723BE', if_true: files('rtl8723be_pci.c'))
system_ss.add(when: 'CONFIG_FSL_ENETC_VF', if_true: files('fsl_enetc_vf_pci.c'))
system_ss.add(when: 'CONFIG_FST', if_true: files('fst_pci.c'))
system_ss.add(when: 'CONFIG_RTL8821AE', if_true: files('rtl8821ae_pci.c'))
system_ss.add(when: 'CONFIG_GEM', if_true: files('gem_pci.c'))
system_ss.add(when: 'CONFIG_GMA500', if_true: files('gma500_pci.c'))
system_ss.add(when: 'CONFIG_GOKU_UDC', if_true: files('goku_udc_pci.c'))
system_ss.add(when: 'CONFIG_GPIO_THUNDERX', if_true: files('gpio_thunderx_pci.c'))
system_ss.add(when: 'CONFIG_GXT4500', if_true: files('gxt4500_pci.c'))
system_ss.add(when: 'CONFIG_HIBMC_DRM', if_true: files('hibmc_drm_pci.c'))
system_ss.add(when: 'CONFIG_HIBMCGE', if_true: files('hibmcge_pci.c'))
system_ss.add(when: 'CONFIG_SAA7134', if_true: files('saa7134_pci.c'))
system_ss.add(when: 'CONFIG_SAA7164', if_true: files('saa7164_pci.c'))
system_ss.add(when: 'CONFIG_HINIC', if_true: files('hinic_pci.c'))
system_ss.add(when: 'CONFIG_SATA_MV', if_true: files('sata_mv_pci.c'))
system_ss.add(when: 'CONFIG_SATA_NV', if_true: files('sata_nv_pci.c'))
system_ss.add(when: 'CONFIG_SATA_PROMISE', if_true: files('sata_promise_pci.c'))
system_ss.add(when: 'CONFIG_SATA_SIL', if_true: files('sata_sil_pci.c'))
system_ss.add(when: 'CONFIG_SATA_SIS', if_true: files('sata_sis_pci.c'))
system_ss.add(when: 'CONFIG_SATA_SVW', if_true: files('sata_svw_pci.c'))
system_ss.add(when: 'CONFIG_SATA_ULI', if_true: files('sata_uli_pci.c'))
system_ss.add(when: 'CONFIG_SATA_VIA', if_true: files('sata_via_pci.c'))
system_ss.add(when: 'CONFIG_SDV_GPIO', if_true: files('sdv_gpio_pci.c'))
system_ss.add(when: 'CONFIG_SERIAL', if_true: files('serial_pci.c'))
system_ss.add(when: 'CONFIG_HME', if_true: files('hme_pci.c'))
system_ss.add(when: 'CONFIG_HPILO', if_true: files('hpilo_pci.c'))
system_ss.add(when: 'CONFIG_HPWDT', if_true: files('hpwdt_pci.c'))
system_ss.add(when: 'CONFIG_HSU_DMA_PCI', if_true: files('hsu_dma_pci_pci.c'))
system_ss.add(when: 'CONFIG_I2C_DESIGNWARE_PCI', if_true: files('i2c_designware_pci_pci.c'))
system_ss.add(when: 'CONFIG_SIS96X_SMBUS', if_true: files('sis96x_smbus_pci.c'))
system_ss.add(when: 'CONFIG_SJA1000_PLX_PCI', if_true: files('sja1000_plx_pci_pci.c'))
system_ss.add(when: 'CONFIG_I2C_THUNDERX', if_true: files('i2c_thunderx_pci.c'))
system_ss.add(when: 'CONFIG_SKFDDI', if_true: files('skfddi_pci.c'))
system_ss.add(when: 'CONFIG_I3000_EDAC', if_true: files('i3000_edac_pci.c'))
system_ss.add(when: 'CONFIG_I3200_EDAC', if_true: files('i3200_edac_pci.c'))
system_ss.add(when: 'CONFIG_SM501', if_true: files('sm501_pci.c'))
system_ss.add(when: 'CONFIG_I5400_EDAC', if_true: files('i5400_edac_pci.c'))
system_ss.add(when: 'CONFIG_SM750FB', if_true: files('sm750fb_pci.c'))
system_ss.add(when: 'CONFIG_I5500_TEMP', if_true: files('i5500_temp_pci.c'))
system_ss.add(when: 'CONFIG_I6300ESB_TIMER', if_true: files('i6300ESB_timer_pci.c'))
system_ss.add(when: 'CONFIG_SMSC9420', if_true: files('smsc9420_pci.c'))
system_ss.add(when: 'CONFIG_SMTCFB', if_true: files('smtcfb_pci.c'))
system_ss.add(when: 'CONFIG_I740FB', if_true: files('i740fb_pci.c'))
system_ss.add(when: 'CONFIG_I801_SMBUS', if_true: files('i801_smbus_pci.c'))
system_ss.add(when: 'CONFIG_I82975X_EDAC', if_true: files('i82975x_edac_pci.c'))
system_ss.add(when: 'CONFIG_SND_AD1889', if_true: files('snd_ad1889_pci.c'))
system_ss.add(when: 'CONFIG_SND_ALS4000', if_true: files('snd_als4000_pci.c'))
system_ss.add(when: 'CONFIG_SND_ATIIXP_MODEM', if_true: files('snd_atiixp_modem_pci.c'))
system_ss.add(when: 'CONFIG_IAVF', if_true: files('iavf_pci.c'))
system_ss.add(when: 'CONFIG_SND_AZT3328', if_true: files('snd_azt3328_pci.c'))
system_ss.add(when: 'CONFIG_SND_CA0106', if_true: files('snd_ca0106_pci.c'))
system_ss.add(when: 'CONFIG_SND_CMIPCI', if_true: files('snd_cmipci_pci.c'))
system_ss.add(when: 'CONFIG_SND_CS5535AUDIO', if_true: files('snd_cs5535audio_pci.c'))
system_ss.add(when: 'CONFIG_ICP_MULTI', if_true: files('icp_multi_pci.c'))
system_ss.add(when: 'CONFIG_IDPF', if_true: files('idpf_pci.c'))
system_ss.add(when: 'CONFIG_SND_EMU10K1X', if_true: files('snd_emu10k1x_pci.c'))
system_ss.add(when: 'CONFIG_IE31200_EDAC', if_true: files('ie31200_edac_pci.c'))
system_ss.add(when: 'CONFIG_IFCVF', if_true: files('ifcvf_pci.c'))
system_ss.add(when: 'CONFIG_SND_ENS1370', if_true: files('snd_ens1370_pci.c'))
system_ss.add(when: 'CONFIG_SND_ES1938', if_true: files('snd_es1938_pci.c'))

system_ss.add(when: 'CONFIG_SND_ES1968', if_true: files('snd_es1968_pci.c'))
system_ss.add(when: 'CONFIG_SND_HDA_INTEL', if_true: files('snd_hda_intel_pci.c'))
system_ss.add(when: 'CONFIG_SND_HDSP', if_true: files('snd_hdsp_pci.c'))
system_ss.add(when: 'CONFIG_SND_HDSPM', if_true: files('snd_hdspm_pci.c'))
system_ss.add(when: 'CONFIG_SND_INTEL8X0M', if_true: files('snd_intel8x0m_pci.c'))
system_ss.add(when: 'CONFIG_IGBVF', if_true: files('igbvf_pci.c'))
system_ss.add(when: 'CONFIG_IGEN6_EDAC', if_true: files('igen6_edac_pci.c'))
system_ss.add(when: 'CONFIG_SND_MAESTRO3', if_true: files('snd_maestro3_pci.c'))
system_ss.add(when: 'CONFIG_INIA100', if_true: files('inia100_pci.c'))
system_ss.add(when: 'CONFIG_SND_PCI_ACP3X', if_true: files('snd_pci_acp3x_pci.c'))
system_ss.add(when: 'CONFIG_SND_PCI_ACP6X', if_true: files('snd_pci_acp6x_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_ETH_PCI', if_true: files('intel_eth_pci_pci.c'))
system_ss.add(when: 'CONFIG_SND_RME32', if_true: files('snd_rme32_pci.c'))
system_ss.add(when: 'CONFIG_SND_RME96', if_true: files('snd_rme96_pci.c'))
system_ss.add(when: 'CONFIG_SND_RME9652', if_true: files('snd_rme9652_pci.c'))
system_ss.add(when: 'CONFIG_SND_SOC_AVS', if_true: files('snd_soc_avs_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_LPSS', if_true: files('intel_lpss_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_QEP', if_true: files('intel_qep_pci.c'))
system_ss.add(when: 'CONFIG_SND_SONICVIBES', if_true: files('snd_sonicvibes_pci.c'))
system_ss.add(when: 'CONFIG_SND_VIA82XX', if_true: files('snd_via82xx_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_MID_PWR', if_true: files('intel_mid_pwr_pci.c'))
system_ss.add(when: 'CONFIG_SND_VIA82XX_MODEM', if_true: files('snd_via82xx_modem_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_PCH_THERMAL', if_true: files('intel_pch_thermal_pci.c'))
system_ss.add(when: 'CONFIG_SND_YMFPCI', if_true: files('snd_ymfpci_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_APL', if_true: files('sof_audio_pci_intel_apl_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_CNL', if_true: files('sof_audio_pci_intel_cnl_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_LNL', if_true: files('sof_audio_pci_intel_lnl_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_NVL', if_true: files('sof_audio_pci_intel_nvl_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_PTL', if_true: files('sof_audio_pci_intel_ptl_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_SKL', if_true: files('sof_audio_pci_intel_skl_pci.c'))
system_ss.add(when: 'CONFIG_SOF_AUDIO_PCI_INTEL_TGL', if_true: files('sof_audio_pci_intel_tgl_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_SCU', if_true: files('intel_scu_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_SST_DRIVER', if_true: files('intel_sst_driver_pci.c'))
system_ss.add(when: 'CONFIG_SOLOS', if_true: files('solos_pci.c'))
system_ss.add(when: 'CONFIG_SPI_PCI1XXXX', if_true: files('spi_pci1xxxx_pci.c'))
system_ss.add(when: 'CONFIG_INTEL_VPU', if_true: files('intel_vpu_pci.c'))
system_ss.add(when: 'CONFIG_STARFIRE', if_true: files('starfire_pci.c'))
system_ss.add(when: 'CONFIG_STMMACETH', if_true: files('stmmaceth_pci.c'))
system_ss.add(when: 'CONFIG_SUNDANCE', if_true: files('sundance_pci.c'))
system_ss.add(when: 'CONFIG_SWITCHTEC', if_true: files('switchtec_pci.c'))
system_ss.add(when: 'CONFIG_IOSF_MBI_PCI', if_true: files('iosf_mbi_pci_pci.c'))
system_ss.add(when: 'CONFIG_IOSM', if_true: files('iosm_pci.c'))
system_ss.add(when: 'CONFIG_IPMI_SI', if_true: files('ipmi_si_pci.c'))
system_ss.add(when: 'CONFIG_TEHUTI', if_true: files('tehuti_pci.c'))
system_ss.add(when: 'CONFIG_TG3', if_true: files('tg3_pci.c'))
system_ss.add(when: 'CONFIG_IPU3_CIO2', if_true: files('ipu3_cio2_pci.c'))
system_ss.add(when: 'CONFIG_IPU3_IMGU', if_true: files('ipu3_imgu_pci.c'))
system_ss.add(when: 'CONFIG_ISCI', if_true: files('isci_pci.c'))
system_ss.add(when: 'CONFIG_ISMT_SMBUS', if_true: files('ismt_smbus_pci.c'))
system_ss.add(when: 'CONFIG_THUNDER_BGX', if_true: files('thunder_bgx_pci.c'))
system_ss.add(when: 'CONFIG_THUNDER_XCV', if_true: files('thunder_xcv_pci.c'))
system_ss.add(when: 'CONFIG_TIFM_7XX1', if_true: files('tifm_7xx1_pci.c'))
system_ss.add(when: 'CONFIG_TLAN', if_true: files('tlan_pci.c'))
system_ss.add(when: 'CONFIG_TOSHSD', if_true: files('toshsd_pci.c'))
system_ss.add(when: 'CONFIG_IXGBEVF', if_true: files('ixgbevf_pci.c'))
system_ss.add(when: 'CONFIG_TULIP', if_true: files('tulip_pci.c'))
system_ss.add(when: 'CONFIG_JMB38X_MS', if_true: files('jmb38x_ms_pci.c'))
system_ss.add(when: 'CONFIG_JME', if_true: files('jme_pci.c'))
system_ss.add(when: 'CONFIG_TW68', if_true: files('tw68_pci.c'))
system_ss.add(when: 'CONFIG_TW686X', if_true: files('tw686x_pci.c'))
system_ss.add(when: 'CONFIG_JSM', if_true: files('jsm_pci.c'))
system_ss.add(when: 'CONFIG_K10TEMP', if_true: files('k10temp_pci.c'))
system_ss.add(when: 'CONFIG_K8TEMP', if_true: files('k8temp_pci.c'))
system_ss.add(when: 'CONFIG_KE_COUNTER', if_true: files('ke_counter_pci.c'))
system_ss.add(when: 'CONFIG_KSZ884XP', if_true: files('ksz884xp_pci.c'))
system_ss.add(when: 'CONFIG_KVASER_PCI', if_true: files('kvaser_pci_pci.c'))
system_ss.add(when: 'CONFIG_KVASER_PCIEFD', if_true: files('kvaser_pciefd_pci.c'))
system_ss.add(when: 'CONFIG_TXGBEVF', if_true: files('txgbevf_pci.c'))
system_ss.add(when: 'CONFIG_LABPC_PCI', if_true: files('labpc_pci_pci.c'))
system_ss.add(when: 'CONFIG_ULI526X', if_true: files('uli526x_pci.c'))
system_ss.add(when: 'CONFIG_VIA_RHINE', if_true: files('via_rhine_pci.c'))
system_ss.add(when: 'CONFIG_LEDS_SS4200', if_true: files('leds_ss4200_pci.c'))
system_ss.add(when: 'CONFIG_VIA_SDMMC', if_true: files('via_sdmmc_pci.c'))
system_ss.add(when: 'CONFIG_LOONGSON_SPI_PCI', if_true: files('loongson_spi_pci_pci.c'))
system_ss.add(when: 'CONFIG_LOONGSON', if_true: files('loongson_pci.c'))
system_ss.add(when: 'CONFIG_VMD', if_true: files('vmd_pci.c'))
system_ss.add(when: 'CONFIG_VME_TSI148', if_true: files('vme_tsi148_pci.c'))
system_ss.add(when: 'CONFIG_LPC_ICH', if_true: files('lpc_ich_pci.c'))
system_ss.add(when: 'CONFIG_LPC_SCH', if_true: files('lpc_sch_pci.c'))
system_ss.add(when: 'CONFIG_LYNX_PCI_DRIVER', if_true: files('lynx_pci_driver_pci.c'))
system_ss.add(when: 'CONFIG_MACB_PCI', if_true: files('macb_pci_pci.c'))
system_ss.add(when: 'CONFIG_VT586B_SMBUS', if_true: files('vt586b_smbus_pci.c'))
system_ss.add(when: 'CONFIG_MATROX_W1', if_true: files('matrox_w1_pci.c'))
system_ss.add(when: 'CONFIG_WANXL', if_true: files('wanXL_pci.c'))
system_ss.add(when: 'CONFIG_MDIO_THUNDER', if_true: files('mdio_thunder_pci.c'))
system_ss.add(when: 'CONFIG_MDPY_FB', if_true: files('mdpy_fb_pci.c'))
system_ss.add(when: 'CONFIG_WDT_PCI', if_true: files('wdt_pci_pci.c'))
system_ss.add(when: 'CONFIG_X38_EDAC', if_true: files('x38_edac_pci.c'))
system_ss.add(when: 'CONFIG_XIRCOM_CB', if_true: files('xircom_cb_pci.c'))
system_ss.add(when: 'CONFIG_YENTA_CARDBUS', if_true: files('yenta_cardbus_pci.c'))
system_ss.add(when: 'CONFIG_ZT5550_HC', if_true: files('zt5550_hc_pci.c'))
system_ss.add(when: 'CONFIG_ME_DAQ', if_true: files('me_daq_pci.c'))
system_ss.add(when: 'CONFIG_MF624', if_true: files('mf624_pci.c'))
system_ss.add(when: 'CONFIG_MF6X4', if_true: files('mf6x4_pci.c'))
system_ss.add(when: 'CONFIG_MGAG200', if_true: files('mgag200_pci.c'))

system_ss.add(when: 'CONFIG_BNX2', if_true: files('bnx2_pci.c'))
system_ss.add(when: 'CONFIG_E100', if_true: files('e100_pci.c'))
system_ss.add(when: 'CONFIG_OCTEONTX_CPT', if_true: files('octeontx_cpt_pci.c'))
system_ss.add(when: 'CONFIG_QAIC', if_true: files('qaic_pci.c'))
system_ss.add(when: 'CONFIG_SC92031', if_true: files('sc92031_pci.c'))
system_ss.add(when: 'CONFIG_HISI_PTT', if_true: files('hisi_ptt_pci.c'))
system_ss.add(when: 'CONFIG_I2C_EG20T', if_true: files('i2c_eg20t_pci.c'))

system_ss.add(when: 'CONFIG_3C59X', if_true: files('3c59x_pci.c'))
system_ss.add(when: 'CONFIG_4XXX', if_true: files('4xxx_pci.c'))
system_ss.add(when: 'CONFIG_8139CP', if_true: files('8139cp_pci.c'))
system_ss.add(when: 'CONFIG_8139TOO', if_true: files('8139too_pci.c'))
system_ss.add(when: 'CONFIG_8250_LPSS', if_true: files('8250_lpss_pci.c'))
system_ss.add(when: 'CONFIG_8250_MID', if_true: files('8250_mid_pci.c'))
system_ss.add(when: 'CONFIG_8250_PERICOM', if_true: files('8250_pericom_pci.c'))
system_ss.add(when: 'CONFIG_8255_PCI', if_true: files('8255_pci_pci.c'))
system_ss.add(when: 'CONFIG_ACARD_AHCI', if_true: files('acard_ahci_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_1032', if_true: files('addi_apci_1032_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_1500', if_true: files('addi_apci_1500_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_1516', if_true: files('addi_apci_1516_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_1564', if_true: files('addi_apci_1564_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_16XX', if_true: files('addi_apci_16xx_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_2032', if_true: files('addi_apci_2032_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_2200', if_true: files('addi_apci_2200_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_3120', if_true: files('addi_apci_3120_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_3501', if_true: files('addi_apci_3501_pci.c'))
system_ss.add(when: 'CONFIG_ADDI_APCI_3XXX', if_true: files('addi_apci_3xxx_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI6208', if_true: files('adl_pci6208_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI7X3X', if_true: files('adl_pci7x3x_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI8164', if_true: files('adl_pci8164_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI9111', if_true: files('adl_pci9111_pci.c'))
system_ss.add(when: 'CONFIG_ADL_PCI9118', if_true: files('adl_pci9118_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI1720', if_true: files('adv_pci1720_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI1723', if_true: files('adv_pci1723_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI1724', if_true: files('adv_pci1724_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI1760', if_true: files('adv_pci1760_pci.c'))
system_ss.add(when: 'CONFIG_ADV_PCI_DIO', if_true: files('adv_pci_dio_pci.c'))
system_ss.add(when: 'CONFIG_AE4DMA', if_true: files('ae4dma_pci.c'))
system_ss.add(when: 'CONFIG_AECTC', if_true: files('aectc_pci.c'))
system_ss.add(when: 'CONFIG_AGPGART_SIS', if_true: files('agpgart_sis_pci.c'))
system_ss.add(when: 'CONFIG_AGPGART_VIA', if_true: files('agpgart_via_pci.c'))
system_ss.add(when: 'CONFIG_ALCOR_PCI', if_true: files('alcor_pci_pci.c'))
system_ss.add(when: 'CONFIG_ALI1535_SMBUS', if_true: files('ali1535_smbus_pci.c'))
system_ss.add(when: 'CONFIG_ALI15X3_SMBUS', if_true: files('ali15x3_smbus_pci.c'))
system_ss.add(when: 'CONFIG_ALX', if_true: files('alx_pci.c'))
system_ss.add(when: 'CONFIG_AMD8111_SMBUS2', if_true: files('amd8111_smbus2_pci.c'))
system_ss.add(when: 'CONFIG_AMD_SPI_PCI', if_true: files('amd_spi_pci_pci.c'))
system_ss.add(when: 'CONFIG_AMPLC_DIO200_PCI', if_true: files('amplc_dio200_pci_pci.c'))
system_ss.add(when: 'CONFIG_AMPLC_PCI224', if_true: files('amplc_pci224_pci.c'))
system_ss.add(when: 'CONFIG_AMPLC_PCI230', if_true: files('amplc_pci230_pci.c'))
system_ss.add(when: 'CONFIG_AMPLC_PCI236', if_true: files('amplc_pci236_pci.c'))
system_ss.add(when: 'CONFIG_AMPLC_PCI263', if_true: files('amplc_pci263_pci.c'))
system_ss.add(when: 'CONFIG_ASILIANTFB', if_true: files('asiliantfb_pci.c'))
system_ss.add(when: 'CONFIG_ATH9K_PCI_OWL_LOADER', if_true: files('ath9k_pci_owl_loader_pci.c'))
system_ss.add(when: 'CONFIG_ATL1', if_true: files('atl1_pci.c'))
system_ss.add(when: 'CONFIG_ATL2', if_true: files('atl2_pci.c'))
system_ss.add(when: 'CONFIG_ATLANTIC', if_true: files('atlantic_pci.c'))

